### ISSUE TITLE
Table of contents not translated in localized docs

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/feedback#1490] opened 2019-05-14 09:13 UTC
**Describe the bug**
In some localized docs, such as [.NET Guide](https://docs.microsoft.com/ru-ru/dotnet/standard/), table of contents are displayed in english, despite its entries are translated in [toc.yml file](https://github.com/dotnet/docs.ru-ru/blob/live/toc.yml)

**To Reproduce**
1. Go to https://docs.microsoft.com/ru-ru/dotnet/standard/ page
2. Table of contents in left panel not translated

**Expected behavior**
Table of contents should be translated into corresponding language

**Screenshots**

![screenshot](https://i.stack.imgur.com/UTUDT.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version 42.17134.1.0

**Comment by sudeepku** [comment] 2019-05-14 22:45
@SonjaSaltzman - could you please review this localization issue?

**Comment by SonjaSaltzman** [comment] 2019-05-15 00:16
Assigning to @DavidPrio cc: @JasonCard

**Comment by JasonCard** [comment] 2019-05-15 04:59
@DavidPrio I'm currently following up on this issue, so reassigning to me.

**Comment by CeciAc** [comment] 2019-05-15 14:43
Duplicate of https://github.com/dotnet/docs.ja-jp/issues/595

**Comment by JasonCard** [comment] 2019-05-16 17:58
Hi @MSDN-WhiteKnight 
Thank you for reporting this issue.
Table of contents are now displaying localized version in live page, so closing this issue.

Kind regards,
Microsoft DOCS International Team
cc @CeciAc @SonjaSaltzman @sudeepku

**Closed by JasonCard** 2019-05-16 17:58 UTC
Labels: loc
