### ISSUE TITLE
下载的pdf文件是中文繁体，请弄成中文简体，只有香港人才会默认这个，中国都是中文简体

### ISSUE THREAD

**Issue by gallop1** [MicrosoftDocs/feedback#1690] opened 2019-07-04 02:56 UTC
下载的pdf文件是中文繁体，请弄成中文简体，只有香港人才会默认这个，中国都是中文简体，这个不好阅读。

**Comment by sudeepku** [comment] 2019-07-05 18:57
@SonjaSaltzman  - please help triage and assign as appropriate.

**Comment by SonjaSaltzman** [comment] 2019-07-06 23:15
@DavidPrio 
Translation: The downloaded pdf file is Chinese traditional, please make a Chinese simplified, only Hong Kong people will acquiesce to this, the mainland is Chinese simplified, this is not easy to read.  Could you please follow up with gallop1 to find out which PDF is the wrong language and address it?

**Comment by CeciAc** [comment] 2019-07-08 15:33
你好，@gallop1
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
**请提供URL**

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by gallop1** [comment] 2019-07-09 02:02
@CeciAc https://docs.microsoft.com/zh-cn/aspnet/overview 这个页面点击下载PDF，然后下载到的是繁体的pdf文档。

**Comment by CeciAc** [comment] 2019-07-18 17:27
@JasonCard please, check this issue, the downloaded PDF is in zh-TW while the page is in zh-CN

**Comment by JasonCard** [comment] 2019-07-18 22:04
@CeciAc I could not repro this issue, but can you? I downloaded PDF from [https://docs.microsoft.com/zh-cn/aspnet/overview](https://docs.microsoft.com/zh-cn/aspnet/overview) and confirmed the downloaded PDF is in Simplified Chinese and not in Traditional Chinese (zh-tw):
![zh-cn_pdf](https://user-images.githubusercontent.com/18313964/61495236-3bb8b180-a96d-11e9-8db7-c839f77b47cb.png)

**Comment by gallop1** [comment] 2019-07-19 12:16
@JasonCard 很明显就是繁体了。You are wrong.

**Comment by JasonCard** [comment] 2019-07-19 16:50
@gallop1 The downloaded PDF from Traditional Chinese (zh-tw) [https://docs.microsoft.com/zh-tw/aspnet/overview](https://docs.microsoft.com/zh-tw/aspnet/overview) matches zh-tw translation:
![zh-tw_pdf](https://user-images.githubusercontent.com/18313964/61551225-73753700-aa09-11e9-8e50-ac5b9b1a2c8f.png)

It look like Simplified and Traditional translations are correct:
![Bing_translator](https://user-images.githubusercontent.com/18313964/61551517-44ab9080-aa0a-11e9-915a-785f93d9e686.png)

I still cannot repro the issue of zh-tw PDF being downloaded from zh-cn page. 
@CeciAc Can you repro this issue?

**Comment by CeciAc** [comment] 2019-07-19 19:44
@JasonCard I'll check this with our LMs, I'll keep you posted

**Comment by CeciAc** [comment] 2019-07-22 17:39
@JasonCard 
We checked with our linguist and she confirmed the file is in zh-CN

**Comment by gallop1** [comment] 2019-07-23 02:02
@CeciAc It's impossible, my side download is really a traditional type pdf.
![image](https://user-images.githubusercontent.com/11223081/61677112-e85daf00-ad30-11e9-8f3c-d461c70ad0f5.png).You can see this picture.

**Comment by CeciAc** [comment] 2019-07-23 15:17
@JasonCard @gallop1 
I cannot repro the contributor's issue.
I downloaded both PDFs and they match each web translation.

![imagen](https://user-images.githubusercontent.com/26746247/61724072-970aeb00-ad43-11e9-9cdf-c95841ab1165.png)

**Comment by JasonCard** [comment] 2019-07-23 17:17
@CeciAc Thank you for confirming. From looking at the last screenshot from @gallop1, individual characters are highlighted, so it looks like the contributor is pointing out that some individual characters are Traditional Chinese instead of Simplified Chinese. I confirmed that those highlighted characters in PDF are same in live page, so PDF is not the issue.
[https://docs.microsoft.com/zh-cn/aspnet/web-forms/overview/getting-started/hands-on-labs/using-page-inspector-in-visual-studio-2012](https://docs.microsoft.com/zh-cn/aspnet/web-forms/overview/getting-started/hands-on-labs/using-page-inspector-in-visual-studio-2012). 
![zh-cn_live](https://user-images.githubusercontent.com/18313964/61732139-cfa1c900-ad31-11e9-9f71-0dd9db2dd8bf.png)
I checked with native Simplified Chinese speaker and feedback was that some of those highlighted characters can be used for both Simplified and Traditional Chinese. Can you please help to double check with your Language Moderator?

**Comment by gallop1** [comment] 2019-07-25 01:55
@CeciAc,@JasonCard，Some documents are traditional, and I hope all of them are simplified. Although I can't list all of them, it's necessary because it affects my reading.

**Comment by CeciAc** [comment] 2019-07-30 20:42
Hello, @gallop1 
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by gallop1** [comment] 2019-07-31 02:14
@CeciAc Maybe I got it wrong, but your fonts are not good-looking, making me feel like a little traditional. I'm generally used to using the new song, but the pdf you downloaded feels a little traditional.
![image](https://user-images.githubusercontent.com/11223081/62178529-fa1c0380-b37b-11e9-961a-c066f24c4efd.png)

**Comment by SunnyDeng** [comment] 2019-07-31 20:44
您好 @gallop1 ，
感谢您对我们文档质量的关注与支持！关于您提到的几个问题，请参考如下：
1. 理解您因为字体可能会产生的误解，但是这篇文档确实是简体中文文档。
2. 在PDF中确实存在字体混淆的问题，我们已经与开发部门取得联系，争取早日解决！
PDF下载是我们启用不久的新功能，我们正协力测试纠正其中可能出现的其他问题。欢迎您继续为中文文档提供宝贵意见！

**Comment by gallop1** [comment] 2019-08-07 02:02
@sudeepku,@CeciAc,@SunnyDeng Do you have any rewards for feedback? like money。I look forward to it.

**Comment by SonjaSaltzman** [comment] 2020-04-10 18:25
@JasonCard can this be closed?

**Comment by JasonCard** [comment] 2020-04-10 19:05
Closing this issue as the font issue for Asian languages in PDF is tracked internally, but is in backlog with no ETA at this time.

**Closed by JasonCard** 2020-04-10 19:05 UTC
Labels: Pri3, loc
