### ISSUE TITLE
MS Docs I18l: Please switch off English overlays

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#174] opened 2018-03-06 22:53 UTC
Reading the German edition of MS Docs is rather cumbersome and irritating.

The way the two language versions are presented on the same page is utterly confusing and annoying. These overlays popping up whenever the mouse cursor accidentally hovers over a paragraph very much interfere with the process of reading, particularly when the page is being scrolled using the keyboard while the mouse pointer just rests on the page. This is also true when the reader is about to set a temporary bookmark to a paragraph with the mouse pointer or when the reader wants to select and/or copy a few words from the text.

Instead of showing these disturbing overlay pop-ups, I'd like to suggest to add kind of a navigation bar to the left (or right) text page border (i.e. outside the actual text). When clicking (or, alternatively, hovering) this bar, the corresponding paragraph should temporarily display in English.

Here's the link depicting details plus some visuals to my suggestion:

https://social.msdn.microsoft.com/Forums/en-US/5e530984-edf6-4aed-9a21-bd19657f65a3/msdn-library-international-please-switch-off-english-overlays

----------
⚠ Idea migrated from UserVoice

**Created By:** AxelD
**Created On:** 2017/03/07 17:49:35 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment] 2018-03-07 02:39
@SonjaSaltzman @nokura as FYI on the ask.

**Comment by dend** [comment] 2018-03-07 17:07
Duplicate of #23

**Closed by dend** 2018-03-07 17:07 UTC
Labels: enhancement, triaged
