### ISSUE TITLE
Reintroduce link to original page for translated pages

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#107] opened 2018-03-06 22:52 UTC
At least in my language (German) the result of the automatic translation is often really bad, especially regarding the structure of the sentences. To use the popup windows referring to the original page is quite annoying if the complete page is translated badly. In previous versions there were links to the original English page, please reintroduce them. Would help a lot!
Example of bad translation: https://docs.microsoft.com/de-de/sql/odbc/reference/syntax/sqlcolumns-function

----------
⚠ Idea migrated from UserVoice

**Created By:** Susanne
**Created On:** 2017/10/12 10:44:40 +0000
**Votes at Migration:** 10
**Supporters at Migration:** 10

**Comment by dend** [comment] 2018-03-07 17:12
Duplicate of #23

**Closed by dend** 2018-03-07 17:13 UTC
