### ISSUE TITLE
Borken link on DynamicObject documentation page

### ISSUE THREAD

**Issue by danelso** [MicrosoftDocs/feedback#1340] opened 2019-03-29 20:52 UTC
The documentation page for [DynamicObject ](https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicobject?view=netframework-4.7.2) contains a link to "[Creating Wrappers with DynamicObject](https://go.microsoft.com/fwlink/?LinkId=169008) on the C# Frequently Asked Questions blog".

That link redirects to https://devblogs.microsoft.com/csharpfaq/2009/10/19/dynamic-in-c-4-0-creating-wrappers-with-dynamicobject which gives a 404.

I suspect it should point to:
https://devblogs.microsoft.com/csharpfaq/dynamic-in-c-4-0-creating-wrappers-with-dynamicobject/

**Comment by mairaw** [comment] 2019-04-02 19:31
I can't reproduce this error any longer. It was probably fixed with this PR: https://github.com/dotnet/dotnet-api-docs/pull/2044

**Comment by mairaw** [comment] 2019-06-11 05:59
@sudeepku @dendeli-msft please close this issue. I don't have permissions.

**Comment by mairaw** [comment] 2019-06-17 17:41
Issue is fixed. Closing.

**Closed by mairaw** 2019-06-17 17:41 UTC
Labels: content
