### ISSUE TITLE
Documentation for linking a work item to pull request is gone

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/feedback#337] opened 2018-04-27 20:36 UTC
# Documentation for linking a work item to pull request is gone

In the [old documentation](https://www.visualstudio.com/en-us/docs/integrate/api/git/pull-requests/work-items#adding-a-work-item-link
), there used to a page for linking a work item to pull request, now the link just reroute to the [top git level page](https://docs.microsoft.com/en-us/rest/api/vsts/git/#adding-a-work-item-link).  

## Issue Details
Please either add it to the pull request section or add it as an example to the [work item update section](https://docs.microsoft.com/en-us/rest/api/vsts/wit/work%20items/update)

**Comment by Powerhelmsman** [comment] 2018-04-27 21:51
@hellosnow Can you take a look to see if it is by design?

**Comment by dend** [comment] 2018-04-28 00:28
This feels like a @erickson-doug ask 😄

**Comment by Powerhelmsman** [comment] 2018-05-25 17:44
Close as transferring the issue.

**Closed by Powerhelmsman** 2018-05-25 17:44 UTC
Labels: content, triaged
