### ISSUE TITLE
'*' character does not render

### ISSUE THREAD

**Issue by cdmihai** [MicrosoftDocs/feedback#328] opened 2018-04-25 17:41 UTC
Given xml elements containing the '*' character
- like `<term>arbitrary directory depth ("/**/")</term>`
- in https://github.com/aspnet/ApiDocs/blob/live/api/xml/Microsoft.Extensions.FileSystemGlobbing/Matcher.xml#L68

The rendered output does not include the '*' characters:
- like 
![image](https://user-images.githubusercontent.com/2255729/39262738-1aa81274-4875-11e8-9fe6-66cf941d3d24.png)
- in https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.filesystemglobbing.matcher?view=aspnetcore-2.0#remarks

**Comment by Powerhelmsman** [comment] 2018-04-26 05:53
@dend Can you take a look at this

**Comment by dend** [comment] 2018-04-28 00:39
@joelmartinez is this something that we need to encode when we generate the ECMAXML?

**Comment by joelmartinez** [comment] 2018-04-28 00:57
@dend if I’m understanding this ... the issue is stemming from the fact that this content is being translated by ecma2yaml from ecmaxml content into markdown ... so markdown considers the`*` as formatting. The same issue, for example, wouldn’t occur if the `term` was rendered by mdoc’s html renderer. 

This feels like ecma2yaml should process the text content of XML nodes to encode characters that might be misconstrued as markdown elements. **Or** the content should be changed so that the text that is code is properly wrapped in code elements (offhand I can’t rememeber if it’s `<c>` or `<code>`)

**Comment by dend** [comment] 2018-04-28 01:16
@joelmartinez ah, good point.

@TianqiZhang - seems like something we will need to address with ECMA2YAML.

**Comment by Powerhelmsman** [comment] 2018-06-21 05:40
Create a internal bug to track it. https://icm.ad.msft.net/imp/v3/incidents/details/74047411/home

**Comment by Powerhelmsman** [comment] 2018-06-25 19:14
@cdmihai this is due to compatibility issue with the old DFM markdown engine and the indents introduced by and -to- transform. The new engine will fix this. Tianqi tested here https://github.com/aspnet/ApiDocs/commit/e7cd77bd640a80512967428206faf462796bf937 
if you do similar change the issue will resolve.

**Comment by Powerhelmsman** [comment] 2018-06-25 19:16
@cdmihai I will close the issue now. If you have any question related to this issue, we can reopen it and continue the discussion.

**Closed by Powerhelmsman** 2018-06-25 19:16 UTC
Labels: bug, resolved, triaged
