### ISSUE TITLE
Please redirect the old API docs to the new docs or link

### ISSUE THREAD

**Issue by davkean** [MicrosoftDocs/feedback#200] opened 2018-03-07 21:43 UTC
1. Search for "SemaphoreFullException" in google
2. Top hit is this page: https://msdn.microsoft.com/en-us/library/system.threading.semaphorefullexception(v=vs.110).aspx.
3. Visit that page, get note  that says:

![image](https://user-images.githubusercontent.com/1103906/37119834-cfb793ea-22ac-11e8-9f57-9a1c3fb94419.png)

4. Click that link

**Expected:** To be redirect to the new docs equivalent for that page
**Actual:** Get redirect to a front page here: https://docs.microsoft.com/en-us/dotnet/api/?view=netframework-4.7.1

This has resulted in me not using the new site, I just fall back to the old site.

Either redirect to the same page equivalent or just redirect the msdn.microsoft.com docs to their equivalent in docs.microsoft.com.

**Comment by dend** [comment] 2018-03-07 21:59
Duplicate of #86 - this is work in progress and we are working to solve this issue ASAP!

**Closed by dend** 2018-03-07 21:59 UTC

**Comment by davkean** [comment] 2018-03-07 22:02
Thanks!
