### ISSUE TITLE
Internal Link Missing

### ISSUE THREAD

**Issue by wonderboy703** [MicrosoftDocs/feedback#2895] opened 2020-06-24 12:35 UTC
Pretty sure this is still a relevant document.. 

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3

**Comment by mairaw** [comment] 2020-06-30 06:37
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2079

**Closed by mairaw** 2020-06-30 06:37 UTC
Labels: Pri3
