### ISSUE TITLE
Sandbox cannot be activated with "Your appeal has been received" message.

### ISSUE THREAD

**Issue by siri2siri** [MicrosoftDocs/feedback#2306] opened 2019-12-27 02:14 UTC
I'm trying to activate Sandbox in MS learning but it's giving me the message that says "Your appeal has been received. Appeals are reviewed on a first-come, first-served basis, and may take several days to process. If your appeal is approved, you will regain access to sandboxes and other interactive learning resources.
For more information, please check the troubleshooting guidance page. once I click "Activate Sandbox"

My Sandbox worked well (as I remember on 12/20/2019) but later it started to show the above message. How can I check the appeal status? Why is my Sandbox not working? Appreciate if anyone could help. My Sandbox account is srinathravi@outlook.com

Thanks
Srinath

**Comment by docs-product** [comment] 2020-02-05 01:20
Duplicate of #2409

**Closed by docs-product** 2020-02-05 01:20 UTC
