### ISSUE TITLE
Older documentation - script hanging

### ISSUE THREAD

**Issue by AndyWDev** [MicrosoftDocs/feedback#423] opened 2018-06-07 20:16 UTC
When accessing older documentation in docs.microsoft.com that contains the text at the top of the page 'we are no longer updating this content.....'  causes the browser (IE11) to hang when attempting to scroll and navigate the page. One must click the 'stop script' button to get the page to load correctly.  Attempting to scroll the page or perform any action causes the script to hang again.  

The issue seems fine on pages that do not have this link.

An  example is: https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ms461685%28v%3doffice.14%29

Also, there is no feedback/bug reporting on these pages - if the content is wrong or there is a bug with the page (as above) there is no way to report it through the page.  

Also, hitting backspace inside this editor causes the browser to return to its previous page exiting this control. It becomes difficult to edit text if the keyboard has a different action than expected.

**Comment by dend** [comment] 2018-06-07 22:12
Closing as duplicate of #3

**Closed by dend** 2018-06-07 22:12 UTC
Labels: bug, triaged
