### ISSUE TITLE
"Applies To" for overloaded methods needs more precision.

### ISSUE THREAD

**Issue by lambdageek** [MicrosoftDocs/feedback#314] opened 2018-04-20 17:20 UTC
Consider `System.Reflection.Assembly.Load` [documented here for .NETFramework 4.7.2](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.load?view=netframework-4.7.2) and [here for .NET Standard 2.0](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.load?view=netstandard-2.0)

Note that the .NET Framework version has 8 overloads, but the .NET Standard version only has 4.

Now take a look at the `Applies To` section in both versions of the document.  Note that it is identical.  This is rather misleading: of the 8 possible overloads, only 4 are in .NET Standard 2.0, and only 1 in .NET Standard 1.6.

----

For overloaded methods, there should be an "Applies To" subsection for each overload:
 * "Applies to" for `System.Reflection.Assembly.Load(AssemblyName)`,
 * A different "Applies to" for `System.Reflection.Assembly.Load(String)`,
 * A different "Applies to" for `System.Reflection.Assembly.Load(byte[])`,
 * etc

Note that this has _nothing_ to do with `System.Reflection.Assembly.Load` specifically: this is a general problem - _every_ overloaded method in the entire .NET API documentation should have "Applies To" on a per-overload basis, not on a per-method name basis.

**Comment by Powerhelmsman** [comment] 2018-04-20 17:30
@mairaw Can you take a look at this suggestion?

**Comment by mairaw** [comment] 2018-04-20 17:36
Yes, totally agree. I've mentioned that before to @dend but I don't recall if we have an internal bug tracking that ask.

**Comment by Powerhelmsman** [comment] 2018-05-25 17:53
@dend any update?

**Comment by Powerhelmsman** [comment] 2018-06-20 23:13
#log-suggestion @dend

**Comment by botcrane** [comment] 2018-06-20 23:13
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=26082) logged.

**Comment by MartinJohns** [comment] 2018-11-16 09:14
As it currently is the "Applies To" section is near useless. The information in there can't be trusted and used. And unfortunately this issue seems to garner no attention.

**Comment by mairaw** [comment] 2018-12-19 07:42
The repro on the last issue that I closed as a duplicate of this one is a very good example that the information is totally inaccurate when you select a different moniker:
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.cryptostream.-ctor?view=netstandard-2.0

Here's the right versions:
https://apisof.net/catalog/System.Security.Cryptography.CryptoStream..ctor(Stream,ICryptoTransform,CryptoStreamMode,Boolean)

The customer cannot know that we hid the other overloads and that the information is applicable to the union of all overloads, not just that one.

**Comment by mairaw** [comment] 2019-03-08 04:00
From all the customer suggestions we have at the moment, this one would be the one I'd rank the highest from our backlog. As you can see, we keep resolving feedback items as a duplicate of this one.

@dendeli-msft @rloutlaw

**Comment by thomaslevesque** [comment] 2019-10-19 09:32
Any news on this? It's really annoying not to be able to see which overloads are available on which platform...

**Comment by mairaw** [comment] 2019-11-20 08:10
This has now been triaged and prioritized internally with the engineering team. A fix should be coming soon (not sure how soon though).

**Comment by mairaw** [comment] 2019-12-06 00:51
@mimisasouvanh can you confirm what's the tracking work item for this now?
Is it https://ceapex.visualstudio.com/Engineering/_workitems/edit/136805?

**Comment by mimisasouvanh** [comment] 2019-12-30 21:46
@mairaw Yes, it is 136805.

**Comment by keziamicro** [comment] 2021-03-17 22:18
Hello - reviewing and cleaning up some older feedback/issues. Thanks!

**Closed by keziamicro** 2021-03-17 22:18 UTC
Labels: Pri3, assigned-to-pm, content, logged-request

**Comment by mairaw** [comment] 2021-03-17 22:32
This was fixed.
