### ISSUE TITLE
EM_SETSEL description

### ISSUE THREAD

**Issue by aleaksah** [MicrosoftDocs/feedback#1079] opened 2019-01-23 13:26 UTC
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/Controls/em-setsel

**Problem:**
Error in the description.
Existing text:

> If the start is 0 and the end is 1, all the text in the edit control is selected. If the start is 1, any current selection is deselected.

Should be:

> If the start is 0 and the end is -1, all the text in the edit control is selected. If the start is -1, any current selection is deselected.

**Comment by KalleOlaviNiemitalo** [comment] 2019-01-28 22:23
This seems a duplicate of #853

**Comment by aleaksah** [comment] 2019-01-29 06:14
Yes, duplicate. But still unfixed.

**Comment by dendeli-msft** [comment] 2019-01-30 19:00
Duplicate of #853

**Closed by dendeli-msft** 2019-01-30 19:00 UTC
