### ISSUE TITLE
PROCESS_INFORMATION_CLASS

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/feedback#1625] opened 2019-06-15 08:34 UTC
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.

1. https://docs.microsoft.com/en-us/previous-versions/mt767996(v=vs.85)
2. https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-getprocessinformation
3. https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-setprocessinformation

**Problem:**
The content for PROCESS_INFORMATION_CLASS has gone missing and the related APIs GetProcessInfo and SetProcessInfo don't have more information on this type.

It should list the following entries:
typedef enum _PROCESS_INFORMATION_CLASS {
    ProcessMemoryPriority,
    ProcessMemoryExhaustionInfo,
    ProcessAppMemoryInfo,
    ProcessInPrivateInfo,
    ProcessPowerThrottling,
    ProcessReservedValue1,           
    ProcessTelemetryCoverageInfo,
    ProcessProtectionLevelInfo,
    ProcessLeapSecondInfo,
    ProcessInformationClassMax
} PROCESS_INFORMATION_CLASS;

**Comment by GH-Rake** [comment] 2019-07-06 21:54
Confirmed, still an issue

**Comment by ryanmajidi** [comment] 2019-07-24 23:52
@GrantMeStrength Can you please take a look at this issue?

**Comment by 0xThiebaut** [comment] 2019-10-31 08:45
This vanished documentation is still an issue.

**Comment by drewbatgit** [comment] 2019-10-31 17:46
Sorry for the delay on this. I will take ownership of this issue and should have an update in a few days.

**Comment by asklar** [comment] 2020-05-04 08:31
@drewbatgit it's been 7 months, could you please provide an update? the PROCESS_INFORMATION_CLASS page seems to have gone missing completely now 
![image](https://user-images.githubusercontent.com/22989529/80948428-e720de80-8da6-11ea-82f7-1961be9d8fd2.png)

**Comment by drewbatgit** [comment] 2020-05-04 19:56
@asklar I apologize for letting this issue fall through the cracks. I've investigated this issue today and have determined that the API reference page for this API was checked into our old content management system in 2015 but it was explicitly excluded from the documentation build. It appeared in the migrated content due to a quirk in the content migration process. I am currently attempting to track down information as to whether this API reference page was excluded intentionally and, if not, to get descriptions for the enumeration fields from a subject matter expert. This is at the top of my priority list and I will follow up as soon as I have any new information to share.

**Comment by drewbatgit** [comment] 2020-05-11 18:07
@asklar - I consulted with the team that currently owns this feature and we were unable to determine why this API was manually configured to be omitted from the documentation, so I've added a new page for the API. The new page includes the information that was in the previous page and some new information I was able to gather from the source files. A few members of the enumeration that were undocumented are not used by the system and therefore are documented as "reserved". Thank you for calling this issue to our attention!

**Closed by drewbatgit** 2020-05-11 18:07 UTC
Labels: Pri3, content

**Comment by asklar** [comment] 2020-05-11 18:32
@drewbatgit thank you for fixing this page. The `ProcessInPrivateInfo` _is_ actually used even though we've marked it as ignored. I was trying to file a new github issue for that but I don't see the link to do so?

**Comment by drewbatgit** [comment] 2020-05-12 17:58
@asklar - What info do you have on ProcessInPrivateInfo? If you share it here, I'll get it into the doc.

**Comment by asklar** [comment] 2020-05-12 21:53
@drewbatgit ProcessInPrivateInfo is used to set a process as running in "InPrivate" mode (e.g. Edge uses this). There is a guarantee about telemetry being blocked from processes marked as InPrivate but the code owners need to make that explicit :)
