### ISSUE TITLE
CRITICAL - not possible to login or register to learn and pass certifications

### ISSUE THREAD

**Issue by UintraContact** [MicrosoftDocs/feedback#1140] opened 2019-02-10 14:23 UTC
Hi, i am really stuck here https://techprofile.microsoft.com/en-US/register and cant login with my existing account, neither register new. it always says, "You are already registered." regardless whether i try to login or register!

this is already 3 times i have duplicated the same critical issue + sent 4 emails to learn-microsoft support contact. just curious, what should i do more. to be able to learn how loged on or registered (whatever) user?

thanks in advance for your help!

**Comment by crowcoder** [comment] 2019-02-16 14:38
Same thing is happening for me. Deleting "techprofile" cookie has no effect. In an incognito window at least I get prompted to sign in but then the cycle starts over again. 
This happens at work and at home. Something seems very broken.

**Comment by mairaw** [comment] 2019-08-05 20:29
Duplicate of #1122

**Closed by mairaw** 2019-08-05 20:29 UTC
Labels: duplicate, learn
