### ISSUE TITLE
documentation for decimal incorrect in german

### ISSUE THREAD

**Issue by krechtern** [MicrosoftDocs/feedback#2048] opened 2019-10-17 08:33 UTC
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
[Decimal Struct (System)](https://docs.microsoft.com/de-de/dotnet/api/system.decimal?view=netframework-4.8)

**Problem:**
The german article describes that a decimal has a range from negativ 337 to positiv 337. This is not correct. It should be `79.228.162.514.264.337.593.543.950.335`. This could lead to huge misunderstandings.

**Comment by mairaw** [comment] 2019-10-17 08:50
@JasonCard please take a look at this issue that is happening at the ..NET API docs in German.

**Comment by JasonCard** [comment] 2019-10-17 17:52
@DavidPrio please help to follow up on this MT loc issue.

**Comment by JasonCard** [comment] 2019-10-17 20:36
@CeciAc Could you please help to check and let us know if this translation issue was from TM or MT?
cc @ishasahni1

**Comment by CeciAc** [comment] 2019-10-17 20:45
Hi @JasonCard 
I just assigned this issue to the engineer teams to investigate.
Due to time zones differences, they won't be able to check it until tomorrow

We'll keep you posted

**Comment by CeciAc** [comment] 2019-10-18 11:40
Hi @JasonCard 
the team confirmed this was an MT issue which affected other languages, too
They were already fixed and we are waiting for staging.
best

**Comment by JasonCard** [comment] 2019-10-18 16:42
Thank you, @CeciAc for confirming!

**Comment by CeciAc** [comment] 2019-11-06 11:25
Hi team, 
we fixed the issue in de-DE and other locales where it repro but the fix is not live yet
we just re processed the file and are waiting for staging

**Comment by CeciAc** [comment] 2019-11-26 17:49
Hello, @krechtern
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/dotnet/api/system.decimal?view=netframework-4.8

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team

**Closed by CeciAc** 2019-11-26 17:49 UTC
Labels: loc
