### ISSUE TITLE
Badges and trophies

### ISSUE THREAD

**Issue by javierbragazzi** [MicrosoftDocs/feedback#1994] opened 2019-10-03 01:24 UTC
Badges and trophies in the profile are not displayed correctly.

![Trofeos](https://user-images.githubusercontent.com/13878358/66092718-675a3980-e563-11e9-8adb-7aa46818fce2.jpg)

**Comment by mairaw** [comment] 2019-10-03 04:18
@docs-product who owns profile and can check this issue?

**Comment by jialge** [comment] 2019-10-10 18:40
Hello.  Thank you for reporting the issue.  We released a new profile design YESTERDAY! :)  Would you like to check again and see if the problem is gone?

**Comment by dendeli-msft** [comment] 2019-12-02 18:32
Closing this issue as it should now be resolved. Thank you for the feedback, @javierbragazzi!

**Closed by dendeli-msft** 2019-12-02 18:32 UTC
Labels: bug
