### ISSUE TITLE
[LOC] Back-Translation "新規-Remotembox"→"New-Remotembox"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2313] opened 2019-12-30 01:44 UTC
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![new-remotemailbox](https://user-images.githubusercontent.com/40815708/71565356-546aed00-2af1-11ea-9d12-b22604d4b05e.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/exchange/federation-and-hybrid/new-remotemailbox?view=exchange-ps"

**Problem:**
What's wrong with the article?
Back-Translation "新規-Remotembox"→"New-Remotembox"

**Comment by mairaw** [comment] 2020-01-07 19:30
@JasonCard who handles PowerShell localization? @hyoshioka0128 has reported a few issues with the localization of some command names.
https://github.com/MicrosoftDocs/feedback/issues/created_by/hyoshioka0128

It's interesting that is even translating content inside code blocks.

**Comment by JasonCard** [comment] 2020-01-08 06:33
@RyanKing77 Could you please help to follow up on this feedback for Japanese translation of PowerShell content?

**Comment by SonjaSaltzman** [comment] 2020-02-27 22:58
@RyanKing77 ping

**Comment by srvbpigh** [comment] 2020-04-02 18:27
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment] 2020-04-03 20:06
Hello @hyoshioka0128 

Thank you for your contribution. 

Contributions on translation problems against machine translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team

**Comment by SonjaSaltzman** [comment] 2020-04-03 20:10
@CeciAc @SunnyDeng THis topic is not even from our content set.  Please do NOT close this. It comes from the https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/New-RemoteMailbox.md repo which is owned by Office team, thus assigning to TinaMcNaboe

**Comment by SonjaSaltzman** [comment] 2020-04-03 20:10
Hi Tina, I think it's from your repo?
cc @SunnyDeng

**Comment by TinaMcN** [comment] 2020-04-03 20:54
@OfficeGlobal please human translate the article.  @Soran-M FYI, MT issue in PowerShell content. @TinaMcN

**Comment by OfficeGlobal** [comment] 2020-04-06 12:06
Working on a fix

**Comment by OfficeGlobal** [comment] 2020-04-15 06:42
@hyoshioka0128 the article was HumanTranslated and published live, the issue is fixed

**Closed** 2020-04-15 22:04 UTC
Labels: Pri3, loc
