### ISSUE TITLE
Unauthorized sandbox use detected. Your sandbox access has been removed.

### ISSUE THREAD

**Issue by krugarmatt** [MicrosoftDocs/feedback#2383] opened 2020-01-15 10:21 UTC
I recently started one of the tutorials on Microsoft Learn (https://docs.microsoft.com/en-us/learn/modules/create-azure-storage-account/) and when I got to step 5, where a sandbox account is required, I was unable to activate the sandbox and was told that the reason was "**Unauthorized sandbox use detected**" and I could appeal the issue.

I submitted an appeal and after several days, I tried activating the sandbox again. This time however, I received a message stating "**Unauthorized sandbox use detected. Your sandbox access has been removed.**" and there is no option to appeal. Please see exact message below:

![microsoft_learning_sandbox_removed](https://user-images.githubusercontent.com/7726098/72425428-18d65100-3788-11ea-8fa2-966741a5c514.png)

I have completed many tutorials on the site already and never had this issue. I use the sandbox purely for the purposes of the tutorials and have not broken the terms of use so this issue has come as quite a surprise.

Is it possible for the sandbox to be re-enabled for my account please?

**Comment by docs-product** [comment] 2020-02-05 01:16
Duplicate of #2409

**Closed by docs-product** 2020-02-05 01:16 UTC
