### ISSUE TITLE
Italian: page template for 'This topic applies for:' is not correct

### ISSUE THREAD

**Issue by DueErre** [MicrosoftDocs/feedback#203] opened 2018-03-08 22:38 UTC
# Idea Title

Firts part of articles reports "This topic applies to:" section, and is not part of the content of the article. This phrase is not translate correctly, maybe on template for the page.

## Issue Details

In italian language the phrase "This topic applies to:" can be translated as "Questo argomento si applica a:" but in your template is translated as "In questo argomento si applica a:", and it is wrong.
You can find it in all pages.
![image](https://user-images.githubusercontent.com/23506404/37180533-acbd9538-2329-11e8-842d-4a92922f1043.png)

**Comment by Powerhelmsman** [comment] 2018-03-08 22:41
@SonjaSaltzman This is a translation issue. Can you take a look?

**Comment by SonjaSaltzman** [comment] 2018-03-08 22:54
@swgupt could you please have this reviewed and fixed as needed?

**Comment by swgupt** [comment] 2018-03-08 23:09
Thanks for bringing this to my attention. I am looking into it.

**Comment by ishasahni1** [comment] 2018-03-27 19:09
@DueErre @Powerhelmsman @SonjaSaltzman @swgupt Thank you for bringing this to our attention. The issue is fixed now for all pages across SQL.

**Closed** 2018-03-27 19:29 UTC
Labels: content, triaged
