### ISSUE TITLE
unable to active sandbox

### ISSUE THREAD

**Issue by StevenFlyover** [MicrosoftDocs/feedback#2411] opened 2020-01-21 13:47 UTC
**Link to article:**
https://docs.microsoft.com/en-us/learn/modules/persist-data-ef-core/2-setup-environment

**Problem:**
first time to used. but display following error when active the sandbox.
"Unauthorized sandbox use detected. Your sandbox access has been removed."

**Comment by docs-product** [comment] 2020-02-05 01:20
Duplicate of #2409

**Closed by docs-product** 2020-02-05 01:20 UTC
Labels: assigned-to-pm, bug
