### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by gast128** [MicrosoftDocs/feedback#2402] opened 2020-01-19 12:10 UTC
Not sure what you have done lately with MSDN but most search fails. If I am in Visual Studio 2017 and press F1 to get some documentation it jumps mostly to the main page (e.g. searching for 'is_nothrow_constructible_v' jumps now to the main page ' Visual Studio product family documentation'). If I enter "all_of" in the search bar I get whole list of entries contain 'ALL'; none of them points to std::all_of.

MSDN documentation used to be one of the best. Now it's one of the worst due to the difficulty to get at the wright place (and the habit of destroying links and removing old documentation). Use of google and https://en.cppreference.com gets me to the correct documentation of std::all_of.

**Comment by docs-product** [comment] 2020-02-05 01:13
Duplicate of #2410

**Closed by docs-product** 2020-02-05 01:13 UTC
