### ISSUE TITLE
Search Bar not working

### ISSUE THREAD

**Issue by KristianCEliassen** [MicrosoftDocs/feedback#3453] opened 2021-02-05 19:14 UTC
Using MS Edge Version 88.0.705.63 (Official build) (64-bit). URL: https://docs.microsoft.com/en-us/

The search bar displayed on the top left section of the page below the content ("docs.microsoft.com
The home for Microsoft documentation and learning for developers and technology professionals.") does not return search result. 

Search result text displayed:
"No results
Sorry, we couldn't find anything that fit your search."

![SearchBar](https://user-images.githubusercontent.com/49496406/107078477-615e1380-67bc-11eb-9ea3-a49734d09ecf.jpg)
![SearchBarResults](https://user-images.githubusercontent.com/49496406/107078478-615e1380-67bc-11eb-9496-0ea41aea6a19.jpg)

**Comment by saper-2** [comment] 2021-02-05 20:33
Same for me, I type in top search field "COALESCE" - nothing found. 
Left "quick" serach don't work either, I type "COALESCE" - nothing 😑 

![obraz](https://user-images.githubusercontent.com/8533673/107085869-5f667580-67f9-11eb-8180-af8ec39f5eb7.png)


The new "DOCS" is far worse than old MSDN witch at least WORKED FINE (and didn't force that annoying automatic translations 💢 ). But be happy, you still a bit better than SAP docs 🤫 .

**Comment by makelix** [comment] 2021-02-08 10:00
I have been having the same issue. The search worked in Edge and/or Chrome but not in Firefox for a couple of days but now it doesn't work at all for me.

Actually Edge Version 88.0.705.63 (Official build) (64-bit) doesn't even open the https://docs.microsoft.com/ page right now.

**Comment by makelix** [comment] 2021-02-12 06:04
See also https://github.com/MicrosoftDocs/feedback/issues/3467

**Comment by gewarren** [comment] 2021-02-12 22:08
This seems to be fixed now, so I'll close the issue. Thanks for letting us know!

**Closed by gewarren** 2021-02-12 22:08 UTC
Labels: Pri3

**Comment by benghaner** [comment] 2021-02-13 17:47
For me, this was caused by my ad blocker. Disabled the ad blocker for Microsoft Docs and that fixed the issue. 😄

**Comment by saper-2** [comment] 2021-02-22 18:10
There should pop-up some kind of list with (quick) search result after typing word in search fields (in left panel above topics tree, and in top search)?
When I type e.g. "CAST" it display like it would working, but it won't display anything... The left-search show something when I use up/down arrow (eventually I find the caption that I'm interested but I need to use up/down), top search behave in the same manner, but at least slapping enter redirect to page with results .

![obraz](https://user-images.githubusercontent.com/8533673/108750645-9058e100-7541-11eb-8e9b-af59d836c36d.png)

Browser Firefox 78.7.0esr, ADB disabled.

**Comment by gewarren** [comment] 2021-02-22 19:48
@saper-2 It's working for me in that same Firefox version. There must be something else blocking it on your machine.

![image](https://user-images.githubusercontent.com/24882762/108761552-d8591300-7503-11eb-96fc-90deee5cddcb.png)
