### ISSUE TITLE
Rendering issues when width reduction of the msdn documentation portal.

### ISSUE THREAD

**Issue by vidyutron** [MicrosoftDocs/feedback#753] opened 2018-10-10 13:08 UTC
![image](https://user-images.githubusercontent.com/12430507/46738237-4f870700-ccbb-11e8-8717-b8539592373a.png)

Repro Step:
Reduce the website to take half width of in Chrome using windows Key + Left/Right Arrow key.
Observation:
Then the side search panel takes up whole area, overlapping the main content.

**Comment by EdisonDa** [comment] 2018-10-11 07:40
@sarah-barrett could you please take a look?

**Comment by sarah-barrett** [comment] 2018-10-11 17:02
@EdisonDa This seems to be a bug, shouldn't it be passed on to Adam's team?

**Comment by EdisonDa** [comment] 2018-10-12 02:54
@vidyutron Thank you for your reaching us. Can you consistently reproduce this issue, could you please kindly share me the page you are visiting? I just random some docs page on Chrome but I could not reproduce that.

**Comment by vidyutron** [comment] 2018-10-12 10:32
Hi, 
providing the link: [https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-run-an-operation-in-the-background](url)

**Comment by EdisonDa** [comment] 2018-10-15 01:16
@vidyutron the problem does not reproduce on my side, @Powerhelmsman could you please try above link to see if the problem repro on your side?

**Comment by Powerhelmsman** [comment] 2018-12-11 18:06
@EdisonDa @vidyutron  I can't repro the issue too. I will close it for now. Let me know if you still have the same issue, I can reopen it.

**Closed by Powerhelmsman** 2018-12-11 18:06 UTC
Labels: assigned-to-pm, needs-more-info
