### ISSUE TITLE
Link content is missing in search results

### ISSUE THREAD

**Issue by ygra** [MicrosoftDocs/feedback#928] opened 2018-12-05 09:14 UTC
On the search page the parts of the summary that are links in the fully-rendered documentation are completely missing. While those links should probably be rendered as normal text in the search results they should not be absent completely.

**To Reproduce**

1. Go to, e.g. https://docs.microsoft.com/en-us/dotnet/api/?view=netframework-4.7&term=DispatcherObject

**Expected behavior**

The Description column which shows the summary of the documentation should show the same text as the fully rendered documentation on its own page. Instead, those parts are missing.

**Screenshots**

Search results with missing words:
![image](https://user-images.githubusercontent.com/1692688/49502805-30999100-f876-11e8-8af8-a56d42e800f4.png)
Documentation page with link where the word was missing:
![image](https://user-images.githubusercontent.com/1692688/49502819-38593580-f876-11e8-8d68-922264c8a65e.png)

**Desktop:**

 - OS: Windows 10 1809
 - Browser Chrome
 - Version 70

**Additional context**

Considering there are still various ways of documentation in the backend (I think there's still a mixture of auto-converted Markdown and the original documentation XML), this might not happen in all cases, but only for some content formats. I havent'checked, though.

**Comment by Powerhelmsman** [comment] 2018-12-08 03:47
@dend Can you take a look at this issue?

**Comment by mairaw** [comment] 2019-02-07 00:35
This is a duplicate of #637

**Comment by dendeli-msft** [comment] 2019-02-12 22:56
Closing as duplicate of #637 - good call, @mairaw!

**Closed by dendeli-msft** 2019-02-12 22:56 UTC
Labels: bug
