### ISSUE TITLE
Mixing bold and italic does not work

### ISSUE THREAD

**Issue by jakrams** [MicrosoftDocs/feedback#371] opened 2018-05-16 08:41 UTC
Markdown code:

![markdown](https://user-images.githubusercontent.com/36191331/40106142-447ace58-58f5-11e8-90fa-082ef199ad65.png)

GitHub result:
***A**ugmented **R**eality*

Preview in Visual Studio Code:

![vscode preview](https://user-images.githubusercontent.com/36191331/40106157-4da39a0a-58f5-11e8-8891-505860af57ae.png)

Preview in MsDocs (online):

![docs preview](https://user-images.githubusercontent.com/36191331/40106177-58e583a6-58f5-11e8-86e4-bc536115bf22.png)

Final result in MsDocs:

![docs final](https://user-images.githubusercontent.com/36191331/40106194-60ad1432-58f5-11e8-90f0-70721cf08bf4.png)

**Comment by dend** [comment] 2018-06-20 00:44
@jakrams can you please confirm whether the underscore syntax works?

**Comment by jakrams** [comment] 2018-06-20 08:07
Yep, that works.

**Comment by Powerhelmsman** [comment] 2018-06-20 15:57
Close as resolved.

**Comment by jakrams** [comment] 2018-06-21 08:07
@Powerhelmsman you know I disagree with the rampant policy at Microsoft to just close tickets for any reason that can be found. I am glad that there is a **workaround** but that doesn't **fix** the bug. The bug is still there, you should still actually fix it, especially since even your very own preview does it correctly, leading people to believe they wrote syntax that will work in the final output. I can understand when the ticket gets low priority, because there is a workaround, but still, it should stay open in the backlog.

Just closing tickets to get rid of them is neither customer-obsessed nor a growth-mindset :-P

**Comment by cillroy** [comment] 2018-06-21 18:54
This is addressed moving to our new markdown parser: Markdig (DocFX)

https://babelmark.github.io/?text=***L***orem 
returns:
<p>
  <em><strong>L</strong></em>orem
</p>

**Comment by Powerhelmsman** [comment] 2018-06-21 19:27
@cillroy Has this feature release now?

**Comment by cillroy** [comment] 2018-06-21 20:50
the resolution is to move the markdown parser to markdig, at the repo level... the issue is resolved with the new parsing solution

**Comment by Powerhelmsman** [comment] 2018-06-21 21:33
Close as resolve

**Closed by Powerhelmsman** 2018-06-21 21:33 UTC
Labels: content, triaged

**Comment by jakrams** [comment] 2018-06-26 07:56
So you actually do have a fix upcoming. Great, thank you. This is an acceptable response to then close the ticket ;-)
