### ISSUE TITLE
DownloadsFolder docs need improvements/more details/examples.

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/feedback#260] opened 2018-03-23 16:24 UTC
## Issue Details

https://docs.microsoft.com/en-us/uwp/api/windows.storage.downloadsfolder

Any files created will always be put in a subfolder for the specific app, but this behavior isn't specified anywhere in the docs.  This is apparently to avoid collisions with other apps...

There's also no examples of using the Create*ForUser functions (and the [User](https://docs.microsoft.com/en-us/uwp/api/windows.system.user) documentation doesn't have any examples of how to get the current user (e.g. from the App OnLaunched event) or otherwise) or that passing null in will act as the current user.

**Comment by dend** [comment] 2018-03-23 17:34
@mijacobs @kevinyr can you help address this?

**Comment by dend** [comment] 2018-05-03 18:44
Ping @kevinyr @mijacobs

**Comment by Powerhelmsman** [comment] 2018-05-25 23:04
The issue is transferred to UWP team

**Closed by Powerhelmsman** 2018-05-25 23:04 UTC
Labels: content, triaged
