### ISSUE TITLE
Missing words in System.Collections.Concurrent description

### ISSUE THREAD

**Issue by kaimikael** [MicrosoftDocs/feedback#1291] opened 2019-03-17 15:11 UTC
In https://docs.microsoft.com/en-us/dotnet/api/index?view=netframework-4.7.2 the description for System.Collections.Concurrent says ”…should be used in place of the corresponding types in the and namespaces…”.
This should be “…should be used in place of the corresponding types in the System.Collections and System.Collections.Generic namespaces…”

**Comment by dendeli-msft** [comment] 2019-03-18 17:26
Duplicate of #637

**Closed by dendeli-msft** 2019-03-18 17:26 UTC
