### ISSUE TITLE
Integrate notebook for F#

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#71] opened 2018-03-06 22:52 UTC
It's awesome that F# is supported on Jupyter notebooks. It could be really beneficial to integrate that into the F# guide (maybe even create the whole guide as a notebook) in order to enable people to run the examples in the browser.

----------
⚠ Idea migrated from UserVoice

**Created By:** Kristijan Vulinovic
**Created On:** 2017/12/07 21:55:34 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment] 2018-05-17 19:41
The issue is transferred to F# issue queue.

**Closed by Powerhelmsman** 2018-05-17 19:41 UTC
Labels: content, triaged
