### ISSUE TITLE
Broken links in docs.microsoft.com

### ISSUE THREAD

**Issue by glippert** [MicrosoftDocs/feedback#2623] opened 2020-03-28 18:55 UTC
For example all of the links in the "Option Module" on this page: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/options

**Comment by gewarren** [comment] 2020-03-30 20:19
Thanks for noting this. It is a dupe of dotnet/docs#17579.

**Closed** 2020-03-30 21:00 UTC
