### ISSUE TITLE
Add filtering by date published

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#132] opened 2018-03-06 22:53 UTC
Search results should have filtering by date published as well as product.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/06/21 17:16:56 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment] 2018-03-07 03:04
Duplicate of #148

**Closed by dend** 2018-03-07 03:04 UTC
