### ISSUE TITLE
Content issue in IOCTL_SCSI_PASS_THROUGH_DIRECT  Doc

### ISSUE THREAD

**Issue by BESTRIVENinCN** [MicrosoftDocs/feedback#1533] opened 2019-05-24 07:10 UTC
**Link to article:**
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddscsi/ni-ntddscsi-ioctl_scsi_pass_through_direct

**Problem:**
"&amp;" should be "&" in C++ code, and also the code seems like has the wrong format.

**Comment by ryanmajidi** [comment] 2019-05-24 22:10
@drewbatgit Can you please take a look at this? I believe the issue is '&' vs '&amp' on the last line of the else block.

**Comment by EliotSeattle** [comment] 2019-05-28 20:48
@MSDN-WhiteKnight submitted PR #500 for this issue, which was accepted and merged this morning.
Thanks!!! 
This issue can be closed as fixed.

**Closed** 2019-06-12 01:59 UTC
Labels: content
