### ISSUE TITLE
docs.microsoft.com Certificates Turkey Web Page Text

### ISSUE THREAD

**Issue by marcoxe** [MicrosoftDocs/feedback#2740] opened 2020-05-13 10:55 UTC
**Is your feature request related to a problem? Please describe.**
Problem is in this page (https://docs.microsoft.com/tr-tr/learn/certifications/) texts is not written by UTF-8. 

**Describe the solution you'd like**
You should use UTF-8 in this page. I noticed just this page. Please check the other pages.

**Describe alternatives you've considered**

**Additional context**
Thanks for feedback.

**Comment by JasonWHowell** [comment] 2020-05-21 04:09
@DavidPrio please take a look at this Loc concern for a learn page. Do we need to change the encoding to UTF-8?

**Comment by JasonWHowell** [comment] 2020-05-21 04:10
#label:loc

**Comment by DavidPrio** [comment] 2020-05-21 13:47
Hi @JasonWHowell Once Label is added, we will be able to import this ticket and start working on it.
@SunnyDeng FYI

**Comment by SunnyDeng** [comment] 2020-05-21 16:36
thanks @JasonWHowell  for the trying!
@SonjaSaltzman Can you change the assignee in this repo? 

@DavidPrio i've created DevOps ticket of this one for your convenience. Please triage and fix as soon as possible there. https://ceapex.visualstudio.com/defaultcollection/CEINTL/_workitems/edit/223649

**Comment by SonjaSaltzman** [comment] 2020-05-21 16:58
Assigned to @DavidPrio

**Comment by srvbpigh** [comment] 2020-05-21 17:17
Hello, @marcoxe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment] 2020-05-21 20:08
Hello, @marcoxe

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

We cannot repro the error, metadata shows the page is in UTF-8.
![image](https://user-images.githubusercontent.com/26746247/82601263-ac2ff080-9b85-11ea-82e4-b27d15aef6c3.png)


Kind regards, 

Microsoft DOCS International Team

**Comment by svick** [comment] 2020-05-21 20:35
@CeciAc While I don't know any Turkish, I suspect the problem is that Turkish characters are garbled. [The Turkish alphabet](https://en.wikipedia.org/wiki/Turkish_alphabet#Letters) does not use the letters "ð" or "þ", which appear several times on the page. And it does use "ğ" or "ı", which don't appear in the text of the page proper.

As a specific example, [this page](https://docs.microsoft.com/tr-tr/learn/certifications/courses/browse/), which looks correct to me, contains the word "Başlangıç", while the page in question contains "baþlangýç". I think that's meant to be the same word ("start", according to Google Translate), but it's displayed incorrectly on this page.

Can you have someone who knows Turkish check whether I'm right?

**Comment by SonjaSaltzman** [comment] 2020-05-21 21:46
This needs to go to Michael Sullivan (cannot get his name to resolve, pinged him offline)

**Comment by Micsullivan** [comment] 2020-05-22 02:56
My team will review and update the page. Thank you for bringing this to our attention.

**Comment by Micsullivan** [comment] 2020-05-22 19:56
We have applied the fix to the live page. Please review.

**Comment by svick** [comment] 2020-05-22 20:17
@Micsullivan From my point of view (of someone who doesn't know Turkish) the issue seems to be fixed.

**Closed** 2020-06-11 23:31 UTC
Labels: P1, Pri3, enhancement
