### ISSUE TITLE
API reference should include packages for classes

### ISSUE THREAD

**Issue by BillWagner** [MicrosoftDocs/feedback#439] opened 2018-06-14 20:15 UTC
From dotnet/docs#320:

>The API reference for a class includes its namespace and assembly, just like it does for .Net Framework on MSDN. But for .Net Core, the NuGet package is much more important than the assembly, but it's not shown.

>This information can be found through https://packagesearch.azurewebsites.net/, but I think it should be included directly in the API reference.

>Showing packages for namespaces would likely be more complicated (since there can be more than one), but I think it would be useful too.

Internal tracking bug: [1039115](https://mseng.visualstudio.com/CSI/_workitems?id=1039115&_a=edit&triage=true)

//cc @Svick @mairaw @dend

**Comment by svick** [comment] 2018-06-14 21:08
Note that I opened the original issue in .Net Core 1.x timeframe. Back then, packages were more important than they are now. Though knowing the package is still useful, especially for package-based libraries like Roslyn or ASP.NET Core.

There's also, [this document in dotnet/designs](https://github.com/dotnet/designs/blob/master/accepted/package-doc/package-doc.md), which proposes how this should work.

**Comment by dend** [comment] 2018-06-20 00:10
Dupe of #72

**Closed by dend** 2018-06-20 00:10 UTC
Labels: enhancement, triaged
