### ISSUE TITLE
DotNet API Browser: Namespace descriptions missing information

### ISSUE THREAD

**Issue by chezzwizz** [MicrosoftDocs/feedback#2171] opened 2019-11-17 18:42 UTC
**Description**
On the 'https://docs.microsoft.com/en-us/dotnet/api/?view=...' page, there is missing information for some of the namespace descriptions. The missing information seems to be related to the process of scraping the information from the individual namespace pages where there are links to any urls at 'https://docs.microsoft.com/en-us/dotnet/api' but does not seem to be affected by urls at 'docs.microsoft.com/visualstudio/msbuild/'.

**To Reproduce**
1. Go to [.NET API Browser](https://docs.microsoft.com/en-us/dotnet/api/?view=netframework-4.8)
2. Scroll down to 'Microsoft.Build.Framework Namespace'
3. Open the [Microsoft.Build.Framework Namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.framework?view=netframework-4.8) page in a separate window or tab
2. Compare the description on the API browser page to the summary on the Namespace page.

**Expected behavior**
Each description should include the same information that the linked page summary has.
(e.g. The description for the Microsoft.Build.Framework Namespace description should read:
 
"The Microsoft.Build.Framework namespace contains the types that define how tasks and loggers interact with the MSBuild engine. For information, see MSBuild."

as opposed to:

"The namespace contains the types that define how tasks and loggers interact with the MSBuild engine. For information, see MSBuild."

**Screenshots**
![image](https://user-images.githubusercontent.com/1437965/69012067-463c8500-0926-11ea-96ce-8ee1b2e749a2.png)

![image](https://user-images.githubusercontent.com/1437965/69012083-7126d900-0926-11ea-9b55-c5aa6523b0a3.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 with Service Pack 1 (Build 7601)
 - Browser Chrome 78.0.3904.97 (64-bit)

**Comment by mlottner** [comment] 2019-11-20 16:24
@chezzwizz Thanks for taking the time to report this issue. 
I've flagged the issue for a member of the .NET experience team to ensure they are aware of it, and see if and how they can help. 

Appreciate your contribution to our community.

**Comment by mimisasouvanh** [comment] 2019-11-20 17:33
@chezzwizz @mlottner We are aware of this issue, and tracking it internally. Thanks!

**Comment by mimisasouvanh** [comment] 2019-12-30 19:41
Duplicate of: https://github.com/MicrosoftDocs/feedback/issues/637

**Comment by mlottner** [comment] 2019-12-31 06:54
@chezzwizz Thanks again for your feedback. 
I'm closing this issue here as the relevant team is aware of it and tracking it internally. Feel free to open additional site feedback cases if/as needed.

**Closed by mlottner** 2019-12-31 06:54 UTC
Labels: content
