### ISSUE TITLE
Include [SerializableAttribute] in .NET Framework Documentation

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#43] opened 2018-03-06 22:52 UTC
The omission of the [SerializableAttribute] in .NET Framework documentation is an bug as far as I'm concerned. I think its because now that Microsoft has the .NET Standard, it's supposedly left to each implementation to tag basic types as serializable or not. I think something is getting lost in the document generation process. MSDN docs are way more accurate. This may change as Docs comes up to speed, but it makes it hard for beginners to make heads or tails out of what they see on the site.

----------
⚠ Idea migrated from UserVoice

**Created By:** Rick Miller
**Created On:** 2017/12/28 15:36:33 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment] 2018-03-07 02:22
@mairaw @terrajobst let me know what you think about this request.

**Comment by dend** [comment] 2018-05-10 17:27
Ping @mairaw @terrajobst. Also @rpetrusha @BillWagner

**Comment by rpetrusha** [comment] 2018-05-10 18:29
@dend, I agree that the serializable attribute should appear in the syntax section. It's one of the more important attributes.

**Comment by BillWagner** [comment] 2018-05-10 18:31
I agree with @rpetrusha 

However, I have one caveat (@terrajobst can provide answers)

IF a type implements `[Serializable]` in one .NET implementation, but not another, that has to be clearly spelled out for types in standard.

**Comment by rpetrusha** [comment] 2018-05-10 18:39
The comment from @BillWagner is important. Since serialization isn't defined by the .NET Standard, it's not necessarily the case that a type marked as serializable on one .NET implementation will be serializable on another. And of course on .NET Standard, the SerializableAttribute isn't applied.

**Comment by mairaw** [comment] 2018-05-10 19:06
I don't understand why this attribute wouldn't show up. Everything should be controlled from the [filter file](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/_filter.xml#L107), no? The only attribute being excluded from System is MonoTODOAttribute.

**Comment by Powerhelmsman** [comment] 2018-05-24 21:47
@dend Can you update the status?

**Comment by dend** [comment] 2018-06-20 00:05
@mairaw @BillWagner @rpetrusha is there an example class you can point me to that should have `SerializableAttribute` but doesn't on docs?

**Comment by BillWagner** [comment] 2018-06-21 15:11
@Dend  Still an issue.

Compare [docs](https://docs.microsoft.com/en-us/dotnet/api/system.collections.arraylist?view=netframework-4.7.2) and [MSDN](https://msdn.microsoft.com/en-us/library/system.collections.arraylist(v=vs.110).aspx)

**Comment by dend** [comment] 2018-06-21 16:23
Looks like Maira already opened an issue for it in the `mdoc` repo: https://github.com/mono/api-doc-tools/issues/273

cc: @joelmartinez

**Comment by mairaw** [comment] 2018-06-22 19:01
I knew we had an issue about this somewhere. Mystery solved! 😄

**Comment by joelmartinez** [comment] 2018-06-22 19:04
yep :) I commented as such on that GH issue, but essentially, it looks like `[Serializable]` is treated differently than other attributes (at least, by Mono.Cecil's API) ... so mdoc just needs to special-case this. 

@mairaw do you think there might be any other fundamental attributes like this that aren't currently represented?

**Comment by mairaw** [comment] 2018-06-22 19:08
It might. We only find those out if we're running SxS comparisons or if a customer reports the issue like here. @dend wondering if we could have the test team helping us with some more testing before we redirect the MSDN to Docs.

**Comment by dend** [comment] 2018-06-25 05:39
@mairaw @joelmartinez we definitely need to hold a bug bash before redirection. Once we validate the newly-generated content, we should review it with the team.

**Comment by dend** [comment] 2018-08-21 03:34
Duplicate of #298

**Closed by dend** 2018-08-21 03:34 UTC
Labels: assigned-to-pm, content, enhancement
