### ISSUE TITLE
Searching.  When you try a keyword.  Filter according to key words. And remove previous search tag from textbox

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#119] opened 2018-03-06 22:53 UTC
While searching. if you have searched some data.  Next time when you enter new keyword.  Previous take place like place holder.  And new entry not show and writin under the place holder.  You need to improve.  

----------
⚠ Idea migrated from UserVoice

**Created By:** Waseem Hussain
**Created On:** 2017/09/18 18:41:05 +0000
**Votes at Migration:** 0
**Supporters at Migration:** 0

**Comment by presleyy** [comment] 2018-03-28 06:57
From the description, that seems be a bug. But can't reproduce the it. A screenshot will be very helpful to understand more about the issue.

**Comment by presleyy** [comment] 2018-06-20 00:41
Tried it again recently, not reproducible according to the description. Need a screenshot for more details, or we could close it for now. @dend @Powerhelmsman

**Comment by Powerhelmsman** [comment] 2018-06-20 02:39
Close as lack of enough information and can't repro.

**Closed by Powerhelmsman** 2018-06-20 02:39 UTC
Labels: assigned-to-pm, enhancement, triaged
