### ISSUE TITLE
.NET API Browser main page: missing parts in Description items

### ISSUE THREAD

**Issue by fneplj** [MicrosoftDocs/feedback#969] opened 2018-12-17 16:44 UTC
**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-2.1

**Problem:**
In the column Description, parts that refer to links to other sections are missing. e.g. for **System.Drawing Namespace**:
"The  namespace provides access to GDI+ basic graphics functionality. More advanced functionality is provided **in the , , and  namespaces**"

should be
"The System.Drawing namespace provides access to GDI+ basic graphics functionality. More advanced functionality is provided in the **System.Drawing.Drawing2D**, **System.Drawing.Imaging**, and **System.Drawing.Text namespaces**."

**Comment by Powerhelmsman** [comment] 2018-12-17 17:23
@dend @presleyy Can you take a loo at this issue?

**Comment by mairaw** [comment] 2018-12-20 00:42
Yes, please fix this. Tagging @Sampy too.

I've asked about this internally on Teams the other day as well. The API browser simply drops the text from see cref links.

**Comment by mairaw** [comment] 2018-12-20 00:53
This is also a duplicate of #637

**Comment by Powerhelmsman** [comment] 2018-12-21 03:09
close as duplicate, we will track it on #637

**Closed by Powerhelmsman** 2018-12-21 03:09 UTC
Labels: bug, duplicate
