### ISSUE TITLE
Navigate to topic from old site

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#31] opened 2018-03-06 22:52 UTC
When coming from MSDN.Microsoft.com, the message box indicates "The .NET API Reference documentation has a new home....".

When you click on the link, the new site does not navigate to the current topic.

for example: I search for response.redirect. The Old MSDN site came up from Google.  Clicked on the link in the message box and had to type in "response.redirect" again.  Just navigate to the topic.

----------
⚠ Idea migrated from UserVoice

**Created By:** Michael O&#39;Brien
**Created On:** 2018/01/30 12:58:21 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment] 2018-03-07 01:44
Duplicate of #86

**Closed by dend** 2018-03-07 01:44 UTC
Labels: in-progress
