### ISSUE TITLE
I cannot search for short classes or properties in API Browser

### ISSUE THREAD

**Issue by zhiliangxu** [MicrosoftDocs/feedback#424] opened 2018-06-08 06:48 UTC
**Describe the bug**
I cannot search for short classes or properties in API Browser.

**To Reproduce**
1. Go to `https://docs.microsoft.com/en-us/dotnet/api/`
2. Type `E` or `PI` in search box and press return key.
3. No result is returned.

**Expected behavior**
I can get search results such as `System.Math.E`, `System.Math.PI` and `Microsoft.Quantum.Extensions.Math.E`.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 66

**Comment by Powerhelmsman** [comment] 2018-06-08 16:04
@dend Can you take a look at this?

**Comment by dend** [comment] 2018-06-21 17:02
Duplicate of #158

**Closed by dend** 2018-06-21 17:02 UTC
Labels: enhancement, triaged
