### ISSUE TITLE
Search needs to have filtering options

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#148] opened 2018-03-06 22:53 UTC
Finding the right article is much too hard on docs.microsoft.com. For example, searching for Server Manager (in Windows Server 2016) brings up 36 000+ results, with the first page all about SQL Server. It should now be possible to filter the results based on product so that I get to Win 2016, or whatever. 

----------
⚠ Idea migrated from UserVoice

**Created By:** Paul Schnackenburg
**Created On:** 2017/05/06 03:26:21 +0000
**Votes at Migration:** 17
**Supporters at Migration:** 17

**Comment by presleyy** [comment] 2018-03-28 06:37
Agree that scenario is painful. We have a feature of adding filters with facets which is exactly the feature described in that feedback.

**Comment by presleyy** [comment] 2018-06-20 00:33
Have a feature about filter and facets working on that.

**Comment by dend** [comment] 2018-07-04 18:21
Duplicate of #38, so closing this item.

**Closed by dend** 2018-07-04 18:21 UTC
Labels: assigned-to-pm, new-feature
