### ISSUE TITLE
ProcessConfigurationSection in ConfigurationBuilder .net 4.7.1

### ISSUE THREAD

**Issue by shahanurreza** [MicrosoftDocs/feedback#252] opened 2018-03-21 14:39 UTC
# Idea Title

Be as descriptive as you can with your idea/bug report/question/suggestion.

## Issue Details

ProcessConfigurationSection is not getting called other than AppSettingsSection. I would like to replace values from the external configuration source but in my custom configurationbuilder ProcessConfigurationSection is not getting called other than AppSettingsSection.

**Comment by dend** [comment] 2018-03-21 18:13
@mairaw @BillWagner as FYI

**Comment by mairaw** [comment] 2018-03-21 18:22
It seems like this is a product question. @csharpfritz can you help?

**Comment by csharpfritz** [comment] 2018-03-21 18:57
This should be opened in the Visual Studio Community, not in the Docs repository.

It is not a bug, as we are able to create a ConfigurationBuilder and attach it to any ConfigurationSection with the configBuilders attribute and see it process the section properly.  If this continues to be an issue, please open a question on https://developercommunity.visualstudio.com/spaces/8/index.html

+ @stephenmolloy @honggit

**Comment by StephenMolloy** [comment] 2018-03-21 19:05
Is this a question about https://github.com/aspnet/MicrosoftConfigurationBuilders? If so, then this is by design. (Actually, it runs on the ConnectionStringsSection as well.) Because this set of config builders is key/value oriented.

The concept of Configuration Builders in the full framework does apply to any _Section_ in config, just like protected config. Not that does not include section groups. So you can't apply a config builder to 'configuration/system.web', but you can to 'configuration/system.web/httpRuntime' or any of the other "sections" contained within system.web.

**Comment by csharpfritz** [comment] 2018-03-21 19:14
No... this is a question about `virtual ConfigurationSection ConfigurationBuilder.ProcessConfigurationSection(ConfigurationSection configSection)`

**Comment by dend** [comment] 2018-03-21 19:38
Resolving this - @shahanurreza please follow the guideline from @csharpfritz on opening the issue in the correct location.

**Closed by dend** 2018-03-21 19:38 UTC
Labels: question, resolved, triaged
