### ISSUE TITLE
Having trouble with the Azure sandbox 

### ISSUE THREAD

**Issue by agyordanov** [MicrosoftDocs/feedback#2436] opened 2020-01-26 15:47 UTC
Hello everyone,

I am new to Azure and Iwant to practice my knowledge. I tried to do the following tutorial:
https://docs.microsoft.com/en-us/learn/modules/welcome-to-azure/4-exercise-create-website

Unfortunately, I couldn't, because I have this error:
"Unauthorized sandbox use detected. Your sandbox access has been removed.
The sandbox may only be used to complete training on Microsoft Learn. Use for any other reason is prohibited, and may result in permanent loss of access to the sandbox. Please review our Terms of Use."

Screenshot here:
![image](https://user-images.githubusercontent.com/60319179/73137722-938e4e80-405b-11ea-9a96-921bad7e0c55.png)

So I can't do it. I would be very thankful if someone help me solving the issue. 
My Azure account is registered with an email: agyordanov@outlook.com

I am looking forward to your reply.

**Comment by mlottner** [comment] 2020-01-28 15:33
@agyordanov  Thanks for reporting this issue. I've asked a member of our Learn team to take a look and report back on the status.
Appreciate you taking the time to contribute to the benefit of our site and community!
@yunyunyunyun Can you please take a look and report back to us on this issue?

**Comment by agyordanov** [comment] 2020-01-28 15:36
Hello @mlottner,

Thank you for your message. Hopefully the issue will be fixed soon and I can continue learning the Azure platform.

**Comment by Pharamus** [comment] 2020-01-29 08:07
Hello @mlottner 
I have exactly the same problem.
An account at outlook.com never used for the Learn module.

**Comment by docs-product** [comment] 2020-02-05 01:18
Duplicate of #2409

**Closed by docs-product** 2020-02-05 01:18 UTC
Labels: bug, learn
