### ISSUE TITLE
Don't auto translate from english if english is spoken!

### ISSUE THREAD

**Issue by rickardp** [MicrosoftDocs/feedback#933] opened 2018-12-07 08:55 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually switch back to English from Swedish. Swedish translation is really poor, but even if it was improved, I'd still prefer English to get the terminology right for Google, Stackoverflow, etc. Having to switch back every time is a distraction from the content.

**Describe the solution you'd like**
If English is among the languages offered by the browser (Accept-Language header), even if another language is first, don't translate by default. You can still translate if English is not in this header. This way the user has a choice (by specifying in their browser settings whether or not they understand English).

**Describe alternatives you've considered**
There are browser extensions to fix this, but I wouldn't be comfortable with the stability and possible privacy impact of those. I think you should not rely on cookies as I (and possibly other developers) frequently clears them, switches browsers, use privacy mode, etc.

**Additional context**
I would be as bold as to say most developers in Europe are comfortable reading English. Maybe the situation is different in e.g. Asia, I don't know. If, for some reason, you don't want to change this globally (which I still think it's the right choice), at least make the choice of default language per country.

**Comment by Powerhelmsman** [comment] 2018-12-08 04:01
@SonjaSaltzman Can you take a look at this feedback?

**Comment by yooakim** [comment] 2018-12-30 09:16
I would also like to use the courses in ENGLISH although I am a SWEDISH speaking person. The translations are not very good and it makes a  lot more sense to do the course material in English. Please add the option to choose the language for the course material.

**Comment by SonjaSaltzman** [comment] 2019-03-05 04:14
@yooakim thank you for your feedback; different users have different preferences (some prefer to read the Swedish translations, some do not).  You can set your preferred language by using the language picker at the bottom left of the page:
![image](https://user-images.githubusercontent.com/15201704/53780577-ea29f180-3eb9-11e9-9096-9ec493bf2868.png)
 Alternatively, you can select the "read in English" toggle (which will persist) in the top right corner: 
![image](https://user-images.githubusercontent.com/15201704/53780611-0f1e6480-3eba-11e9-9e03-fe76cfc4eafd.png)

**Comment by rickardp** [comment] 2019-03-05 08:01
@SonjaSaltzman Your comment was regarding @yooakim’s request, but I just wanted to clarify: I believe this is a different issue altogether.

The original issue was exactly what you wrote, that people have different preferences, and therefore IMHO you should look at the user’s browser preferences before machine translating content. Has there been any updates on the original issue?

**Comment by rickardp** [comment] 2019-03-05 08:06
On a side note, I believe the HTTP Accept-Language header should be amended with “accept-translation: if-not-primary|if-not-spoken|never” or something similar to clarify user intent. But that’s a different story :)

**Comment by SonjaSaltzman** [comment] 2019-03-05 16:01
correct, my comment was to @yooakim.  For the feature: @bodhigautam could you please update about the language preference feature?

**Comment by firdacz** [comment] 2019-11-05 11:12
@bodhigautam A year later, the toggle was removed, the feature requested still not implemented and things got worse.

**Comment by SonjaSaltzman** [comment] 2019-11-05 16:30
Thank you for your feedback - I just responded to your other feedback https://github.com/MicrosoftDocs/feedback/issues/1715 -- it is not our intention to remove the "read in English" toggle, so if you could tell us which documentation (product/URL) you found the problem in, we will make sure to look into it!

**Comment by docs-product** [comment] 2019-11-16 02:25
Duplicate of #462.

**Closed by docs-product** 2019-11-16 02:25 UTC
Labels: loc

**Comment by rickardp** [comment] 2019-11-16 07:20
I don’t think it is a strict duplicate, but I’ll comment in the other one
