### ISSUE TITLE
Xamarin.Android in .Net API Browser isn't actual

### ISSUE THREAD

**Issue by ticotaco72** [MicrosoftDocs/feedback#645] opened 2018-08-30 18:39 UTC
**Link to article: https://docs.microsoft.com/pl-pl/dotnet/api/?view=xamarinandroid-7.1**

Version 8.0 is already available for devs, but there's no documentation for it.

**Comment by conceptdev** [comment] 2018-08-30 19:56
Answered in https://github.com/MicrosoftDocs/xamarin-docs/issues/726

**Comment by Powerhelmsman** [comment] 2018-08-30 20:56
@ticotaco72 Since the issue is answered. I will close it here.

**Closed by Powerhelmsman** 2018-08-30 20:56 UTC
