### ISSUE TITLE
cref summary text won't show in .NET API Browser Description

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#637] opened 2018-08-28 07:38 UTC
Original GitHub issue https://github.com/dotnet/docs/issues/7325 from @imba-tjd 

For example, searching `missing`:
![qq 20180828152637](https://user-images.githubusercontent.com/24759802/44707339-d64e9e80-aad6-11e8-9131-aa67244fbc91.png)
![default](https://user-images.githubusercontent.com/24759802/44707364-e5355100-aad6-11e8-8d0b-047f090acd3f.png)
Source: https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection/Missing.xml#L49

**Comment by Powerhelmsman** [comment] 2018-08-28 16:40
@dend Can you take a look at this?

**Comment by mairaw** [comment] 2018-08-29 06:13
@Sampy might be a better person for this issue

**Comment by Powerhelmsman** [comment] 2018-08-29 16:03
@presleyy Can you work with Sampy on this API browser issue?

**Comment by dend** [comment] 2018-08-29 16:28
@mairaw @Powerhelmsman this is an API Browser feature request - this will be a new detail that we need to implement (it's not a bug per-se :) ) - please assign those to me in the future (_as @Powerhelmsman did earlier_).

**Comment by mairaw** [comment] 2018-08-29 16:36
Good to know.

But your definition of a bug or feature request can get fuzzy 😁 like API Browser should have been designed to support API links from the start and I'm surprised we're only catching this issue now to be honest if it has always been there. I thought it only stopped working instead of never working.

**Comment by dend** [comment] 2018-08-29 17:34
@mairaw the descriptions in the API Browser at launch were intended to be plain-text. We don't resolve any links/CREF entries. As such, anything that is not part of the original design becomes a feature request unless it behaves differently than what it was designed to do 😄

**Comment by mairaw** [comment] 2018-10-26 17:45
Sure. But when the text is being completely dropped, I'd say is a 🐞 
The system should never intend to drop the text from the sentence.

**Comment by dend** [comment] 2018-10-27 00:01
Tracked here: https://ceapex.visualstudio.com/Engineering/_workitems/edit/47430

**Comment by gewarren** [comment] 2019-03-08 21:34
Ironic choice of class name for your example :)

**Comment by mimisasouvanh** [comment] 2020-08-31 21:59
@mairaw This issue has been fixed. Closing.

**Closed by mimisasouvanh** 2020-08-31 21:59 UTC
Labels: Pri3, enhancement

**Comment by mairaw** [comment] 2020-08-31 22:21
Amazing news @mimisasouvanh!
