### ISSUE TITLE
Add versioning to Programming Guides

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#74] opened 2018-03-06 22:52 UTC
I programming guides, if best practices or recommended guidance changes between library versions, provide a way to select the version of .NET (or Core, etc) that you're using. This would be better than always providing docs on the latest versions.

For example, in the C# Programming Guide, Pattern Matching may be the best way of achieving something in the latest code, but it would not be possible with older tooling/frameworks.

Some way to navigate back in time on the docs for older guidance would be really useful.

----------
⚠ Idea migrated from UserVoice

**Created By:** Alvin Ashcraft
**Created On:** 2017/12/07 20:23:47 +0000
**Votes at Migration:** 3
**Supporters at Migration:** 3

**Comment by Powerhelmsman** [comment] 2018-05-17 20:26
The issue is transferred to C# programming content team

**Closed by Powerhelmsman** 2018-05-17 20:26 UTC
Labels: content, triaged
