### ISSUE TITLE
Highlighted code lines in snippets not rendering in Edge

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/feedback#2016] opened 2019-10-09 17:16 UTC
We have a report on the ASP.NET Core docs repo ...

> there is no text (code) in the areas with the light yellow background

... for the doc at https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/using-data-protection?view=aspnetcore-2.1.

I wasn't able to repro it here, and I don't have the Edge version. The community member may be able to respond on that issue to provide additional information if needed.

Our issue: https://github.com/aspnet/AspNetCore.Docs/issues/14942

**Comment by Rick-Anderson** [comment] 2019-10-09 23:02
@wildough57 can you supply an image of what's not rendering correctly?

**Comment by docs-product** [comment] 2019-11-30 01:21
Cannot reproduce the issue, and it seems like the current highlighting works as expected. Closing.

**Closed by docs-product** 2019-11-30 01:21 UTC
