### ISSUE TITLE
"Filter by title" box stops working and throws a bunch of "TypeError: Cannot read property 'split' of undefined"

### ISSUE THREAD

**Issue by Kevin-He-DVHS** [MicrosoftDocs/feedback#495] opened 2018-07-07 02:32 UTC
**Describe the bug**
"Filter by title" is a common search box that is seen on almost every documentation page under [Microsoft Docs](https://docs.microsoft.com). However, recently (sometime between 7/2/2018 - 7/6/2018), you can no longer filter things on certain documentation websites. The text typed into the box is ignored. Examples include [PowerShell Scripting](https://docs.microsoft.com/en-us/powershell/scripting/powershell-scripting?view=powershell-6) and [Windows Server Docs](https://docs.microsoft.com/en-us/windows-server/windows-server).

**To Reproduce**
1. Go to certain pages on Microsoft Docs that has a "Filter by Title" box on it and experiences this bug (Ex. [PowerShell Scripting](https://docs.microsoft.com/en-us/powershell/scripting/powershell-scripting?view=powershell-6), [Windows Server Docs](https://docs.microsoft.com/en-us/windows-server/windows-server))
2. Type something into the box
3. The navigation bar below stays the same, and the following JavaScript exception is thrown *repeatedly* as you type:
##### Chrome Developer tools
```
Uncaught TypeError: Cannot read property 'split' of undefined
    at filterToc (2a5d262e.global.min.js:11167)
    at HTMLInputElement.<anonymous> (2a5d262e.global.min.js:11074)
    at HTMLInputElement.dispatch (jquery-2.2.4.min.js:3)
    at HTMLInputElement.r.handle (jquery-2.2.4.min.js:3)
```
##### Edge Developer tools
```SCRIPT5007: Unable to get property 'split' of undefined or null reference```

**Expected behavior**
The titles in the navigation bar should be filtered based on the input text

**Screenshots**
Detailed Error location:
![chrome error location](https://user-images.githubusercontent.com/32375681/42405847-f06c0bee-8151-11e8-9fbe-d3c492e0a2a7.PNG)
variable `rawScope` seems to be `undefined` here
Demonstration:
![nothing is changed](https://user-images.githubusercontent.com/32375681/42405850-fc838c2c-8151-11e8-8207-36d1cd2a53b0.PNG)
Chrome console:
![doc microsoft com error chrome](https://user-images.githubusercontent.com/32375681/42405858-11f00144-8152-11e8-8e7c-4e6e23190de5.PNG)
Edge console:
![doc microsoft com error edge](https://user-images.githubusercontent.com/32375681/42405864-181ad530-8152-11e8-81ae-c59bc1a22294.PNG)

**Desktop:**
 - OS: [Windows 10 Home build 17134.137]
 - Browser [**Both** Chrome and Edge (likely all browser, but not tested on other browsers)]
 - Version [Chrome 67.0.3396.99, Edge 42.17134.1.0, EdgeHTML 17.17134]

**Additional context**
The problem is probably due to some website updates that contain a JavaScript bug in its code after 7/2/2018. It's likely that the update is only applied to some newly updated websites. The [Archived version of PowerShell Scripting on 7/2/2018](https://web.archive.org/web/20180702012119/https://docs.microsoft.com/en-us/powershell/scripting/powershell-scripting?view=powershell-6) works correctly.

**Comment by Powerhelmsman** [comment] 2018-07-09 16:44
@presleyy this is a bug. Please find the right person to fix ASAP.

**Comment by presleyy** [comment] 2018-07-10 00:29
@adkinn I think this might be caused by the scope fixing for search link. Could you double check that?

**Comment by Powerhelmsman** [comment] 2018-07-11 00:02
@Kevin-He-DVHS thanks for your feedback. The bug is fixed now. Please verify it.

**Closed** 2018-07-11 00:03 UTC
Labels: bug, resolved
