### ISSUE TITLE
Website issue when 100%zoom

### ISSUE THREAD

**Issue by vivekpatel19** [MicrosoftDocs/feedback#685] opened 2018-09-15 04:08 UTC
https://docs.microsoft.com/en-in/windows/uwp/get-started/?ocid=WinClient_Ver1703_Settings_TipCreateApp
![screenshot 76](https://user-images.githubusercontent.com/30730410/45582319-141b3780-b8cb-11e8-8c78-ad186314476c.png)

**Comment by Powerhelmsman** [comment] 2018-09-15 17:55
@ShevaDas Can you take a look at this issue?

**Comment by ShevaDas** [comment] 2018-09-16 04:07
Duplicate of #655, closing.

**Closed by ShevaDas** 2018-09-16 04:07 UTC
Labels: bug
