### ISSUE TITLE
Open source Windows Insider documentation set

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/feedback#444] opened 2018-06-18 23:27 UTC
The Windows Insider documentation set contains pages that are tied to new flights of Windows 10 and are typically out of date/incorrect. Opening these areas up will allow the community to fill in gaps at a much quicker pace and free the team to work on other tasks.

Examples:
https://docs.microsoft.com/en-us/windows-insider/flight-hub/
https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home

**Comment by dend** [comment] 2018-06-18 23:31
Assigning to @lizap as she is working with the Windows Insider team on this task.

**Comment by bleblancMSFT** [comment] 2018-06-18 23:52
Yes, this is by design. We're holding off opening it up to community edits until we are done building out Flight Hub. We're continuing to look at some formatting and other things to improve first. We want to build a solid foundation first. Flight Hub has been up to date for the last 4 weeks as I am personally ensuring its updating every time we hit publish on a flight so it hasn't been out of date in a while. Yes, minor date typos have occurred and been corrected. Thanks!

**Closed** 2018-06-19 00:14 UTC

**Comment by Powerhelmsman** [comment] 2018-06-19 00:15
@riverar Please take a look bleblancMSFT's reply. I will close it so far. If you have other question related to it, we can reopen it to continue the discussion.

**Comment by riverar** [comment] 2018-06-19 00:21
I'm not sure marking this "resolved" or "closed" is appropriate. Shouldn't this be triaged and sit in your backlog until the team decides to definitively reject this or complete the task?

**Comment by bleblancMSFT** [comment] 2018-06-19 00:33
It’s my doc and I’m the PM for Flight Hub. I’m saying it’s good to close for now. Thanks.

Sent from Outlook Mobile<https://aka.ms/qtex0l>.

________________________________

**Comment by riverar** [comment] 2018-06-19 22:12
Resolved: Documentation set is now open source https://github.com/MicrosoftDocs/windows-insider

**Comment by dend** [comment] 2018-06-19 22:16
Thank you for your feedback, @riverar! 🎉
