### ISSUE TITLE
Move old repos from Microsoft org to MicrosoftDocs

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#374] opened 2018-05-17 04:51 UTC
**Is your feature request related to a problem? Please describe.**
There are a few docs repos still under the main Microsoft org https://github.com/Microsoft?utf8=%E2%9C%93&q=docs&type=&language=

**Describe the solution you'd like**
Transfer the repos under the MicrosoftDocs organization

**Describe alternatives you've considered**
These may be intentionally left in the other org because they are published differently, or ar handled by another group

**Additional context**
Some are not repo docs, but more code samples, that might make sense to leave where they are. The repo https://github.com/Microsoft/CEO_CE_Stage_InTuneDocs-pr_ also appears to have been accidentally created and is empty

**Comment by dend** [comment] 2018-06-26 16:50
@nschonni in that regard, some teams and organizations choose to keep their documentation in their own orgs (e.g. `aspnet`, `dotnet`, `mono`) - we have no plans to change that, and our system enables that out-of-the-box. This gives teams the level of control they want over the repos and content there.

**Comment by Powerhelmsman** [comment] 2018-06-26 17:39
@nschonni Thanks for your suggestion. I will close this so far as this is by design and no plan to change. If you have other question related to this, we can re-open it and continue the discussion.

**Comment by nschonni** [comment] 2018-06-26 17:50
@dend sorry for confusing the issue with the `aspnet` ones, but the ones flagged in the original issue don't seem to fit that pattern

**Comment by nschonni** [comment] 2018-07-25 22:10
https://github.com/Microsoft/skype-interviews-docs looks like a docs.micrsoft.com repo, but can't tell where it gets published

**Comment by Powerhelmsman** [comment] 2018-12-11 21:24
@nschonni There is no plan to move this repo to MicrosftDocs, they will manage it by themselves.

**Closed by Powerhelmsman** 2018-12-11 21:24 UTC
Labels: by design, content, wont-fix
