### ISSUE TITLE
Link MSDN page to corresponding docs.microsoft.com page

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#86] opened 2018-03-06 22:52 UTC
For instance, the MSDN page
https://msdn.microsoft.com/en-us/library/system.resources.resourcewriter.aspx
links to API Browser docs.microsoft.com, but it could automatically link to https://docs.microsoft.com/en-us/dotnet/api/system.resources.resourcewriter?view=netframework-4.7.1

----------
⚠ Idea migrated from UserVoice

**Created By:** Sameer
**Created On:** 2017/12/05 19:31:10 +0000
**Votes at Migration:** 9
**Supporters at Migration:** 7

**Comment by IanKemp** [comment] 2018-06-04 08:08
When/if is this going to be actioned? I would have thought it would be trivial to create a redirect rule to send all requests of the form `https://msdn.microsoft.com/<lang>/library/<type>.aspx` to `https://docs.microsoft.com/<lang>/dotnet/api/<type>`... It's so very annoying to hit the old docs page via F1 in Visual Studio or a Google search result, then have to click through to the new docs search and having to re-search for the term you were looking for!

If this isn't going to happen in the immediate future, can you please update the "Note: The .NET API Reference documentation has a new home" section at the top of each old docs page to point to the new docs page.

**Comment by dend** [comment] 2018-06-04 23:54
@IanKemp we are actively working on that, and will have an update in the next couple of weeks!

**Comment by dend** [comment] 2018-06-20 00:12
Duplicate of #50

**Closed by dend** 2018-06-20 00:12 UTC
Labels: assigned-to-pm, in-progress, triaged
