### ISSUE TITLE
Search result Descriptions omit hyperlink text

### ISSUE THREAD

**Issue by atrain247365** [MicrosoftDocs/feedback#732] opened 2018-10-04 12:22 UTC
For example, 
https://docs.microsoft.com/en-us/dotnet/api/?iew=netframework-4.7.2&term=string.IsNullOrEmpty

The Description column has the text 
"Indicates whether the specified string is null or an string." 
rather than
"Indicates whether the specified string is null or an **_Empty_** string." that is displayed when you click the link for the method.

**Comment by presleyy** [comment] 2018-10-08 03:47
This might be a good idea to support rich text for search result description field. But I believe current behavior is by design. @dend your thought?

**Comment by dend** [comment] 2018-10-26 23:56
#log-suggestion @dend 

@presleyy @atrain247365 yes, that is new functionality that we need to add.

**Comment by botcrane** [comment] 2018-10-26 23:56
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=47430) logged.

**Comment by dend** [comment] 2018-10-27 00:00
This is a dupe of #637, though - I will close this item, and keep the internal ticket open for tracking.

**Closed by dend** 2018-10-27 00:00 UTC
Labels: new-feature
