### ISSUE TITLE
Error in CLI command - https://docs.microsoft.com/en-us/learn/modules/control-azure-services-with-cli/5-exercise-create-website-using-the-cli

### ISSUE THREAD

**Issue by JonReu** [MicrosoftDocs/feedback#1777] opened 2019-07-29 19:42 UTC
I always get this error (see at the end):

jonas_reusser@Azure:~$ export RESOURCE_GROUP=Learn-00d7cb47-7ebc-4fa6-a822-dd444b6acbfb
jonas_reusser@Azure:~$ export AZURE_REGION=westus2
jonas_reusser@Azure:~$ export AZURE_APP_PLAN=popupappplan-$RANDOM
jonas_reusser@Azure:~$ export AZURE_WEB_APP=popupwebapp-$RANDOM
jonas_reusser@Azure:~$ az group list --output table
Name                                        Location    Status
------------------------------------------  ----------  ---------
Learn-00d7cb47-7ebc-4fa6-a822-dd444b6acbfb  westus      Succeeded
jonas_reusser@Azure:~$ az group list --query "[?name == '$RESOURCE_GROUP']"
[
  {
    "id": "/subscriptions/946bd22e-d665-41a1-951c-24999bb3847d/resourceGroups/Learn-00d7cb47-7ebc-4fa6-a822-dd444b6acbfb",
    "location": "westus",
    "managedBy": null,
    "name": "Learn-00d7cb47-7ebc-4fa6-a822-dd444b6acbfb",
    "properties": {
      "provisioningState": "Succeeded"
    },
    "tags": {
      "x-created-by": "freelearning",
      "x-created-for": "daab74bc-29bc-4626-9deb-01ad9860d30e"
    },
    "type": null
  }
]
jonas_reusser@Azure:~$ az appservice plan create --name $AZURE_APP_PLAN --resource-group $RESOURCE_GROUP --location $AZURE_REGION
**RequestDisallowedByPolicy - Resource 'popupappplan-2111' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"AppService-SKU","id":"/providers/Microsoft.Management/managementGroups/triplecrown2/providers/Microsoft.Authorization/policyAssignments/7bb64c0aa90247de8b4491c3"},"policyDefinition":{"name":"AppService-SKU","id":"/providers/Microsoft.Management/managementGroups/604c1504-c6a3-4080-81aa-b33091104187/providers/Microsoft.Authorization/policyDefinitions/e790fdfe-5672-403f-9a29-e1aa564ac680"}}]'.**

Sandbox in this site:
https://docs.microsoft.com/en-us/learn/modules/control-azure-services-with-cli/5-exercise-create-website-using-the-cli

I can't finish the learn path!

Thanks

**Comment by mairaw** [comment] 2019-07-29 20:32
@markjulmar can you take a look at this issue?

**Comment by lkoppenol** [comment] 2019-07-31 06:03
I get the same error. 

```
laurens_koppenol@Azure:~$ export RESOURCE_GROUP=Learn-019b069c-b885-400a-8f47-2e009b6990c2
laurens_koppenol@Azure:~$ az group list
[
  {
    "id": "/subscriptions/5e175973-2afd-4610-9172-eecac2215518/resourceGroups/Learn-019b069c-b885-400a-8f47-2e009b6990c2",
    "location": "westus",
    "managedBy": null,
    "name": "Learn-019b069c-b885-400a-8f47-2e009b6990c2",
    "properties": {
      "provisioningState": "Succeeded"
    },
    "tags": {
      "x-created-by": "freelearning",
      "x-created-for": "4075864d-a450-49c0-9933-601f564be709"
    },
    "type": null
  }
]
laurens_koppenol@Azure:~$ export AZURE_REGION=westus2
laurens_koppenol@Azure:~$ export AZURE_APP_PLAN=popupappplan-$RANDOM
laurens_koppenol@Azure:~$ export AZURE_WEB_APP=popupwebapp-$RANDOM
laurens_koppenol@Azure:~$ az appservice plan create --name $AZURE_APP_PLAN --resource-group $RESOURCE_GROUP --location $AZURE_REGION
RequestDisallowedByPolicy - Resource 'popupappplan-3148' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"AppService-SKU","id":"/providers/Microsoft.Management/managementGroups/triplecrown2/providers/Microsoft.Authorization/policyAssignments/7bb64c0aa90247de8b4491c3"},"policyDefinition":{"name":"AppService-SKU","id":"/providers/Microsoft.Management/managementGroups/604c1504-c6a3-4080-81aa-b33091104187/providers/Microsoft.Authorization/policyDefinitions/e790fdfe-5672-403f-9a29-e1aa564ac680"}}]'.
laurens_koppenol@Azure:~$ export AZURE_APP_PLAN=asdasdasd1231312312312313$RANDOMlaurens_koppenol@Azure:~$ az appservice plan create --name $AZURE_APP_PLAN --resource-group $RESOURCE_GROUP --location $AZURE_REGION
RequestDisallowedByPolicy - Resource 'asdasdasd123131231231231331311' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"AppService-SKU","id":"/providers/Microsoft.Management/managementGroups/triplecrown2/providers/Microsoft.Authorization/policyAssignments/7bb64c0aa90247de8b4491c3"},"policyDefinition":{"name":"AppService-SKU","id":"/providers/Microsoft.Management/managementGroups/604c1504-c6a3-4080-81aa-b33091104187/providers/Microsoft.Authorization/policyDefinitions/e790fdfe-5672-403f-9a29-e1aa564ac680"}}]'.
laurens_koppenol@Azure:~$ az appservice plan create --name $AZURE_APP_PLAN --resource-group $RESOURCE_GROUP --location westus
RequestDisallowedByPolicy - Resource 'asdasdasd123131231231231331311' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"AppService-SKU","id":"/providers/Microsoft.Management/managementGroups/triplecrown2/providers/Microsoft.Authorization/policyAssignments/7bb64c0aa90247de8b4491c3"},"policyDefinition":{"name":"AppService-SKU","id":"/providers/Microsoft.Management/managementGroups/604c1504-c6a3-4080-81aa-b33091104187/providers/Microsoft.Authorization/policyDefinitions/e790fdfe-5672-403f-9a29-e1aa564ac680"}}]'.
```

**Comment by joram-s** [comment] 2019-07-31 18:22
I am having the exact same issue as described by OP. Today however something strange happened. 

This morning I tried again starting up the sandbox hoping it would start a session to see if this issue was solved. According to my expectation, no change, exactly same error.

However, this afternoon, I went back again for a reproduction of the issue. But now I couldn't even start the sandbox. When I clicked to activate, it gave me a new return message. 

> **Unauthorized Sandbox use detected. Your sandbox has been terminated.** 

![sandbox issue](https://user-images.githubusercontent.com/53339623/62236947-5f99df80-b3d0-11e9-8bc8-6185f5a6c50a.PNG)

Tried again in a new private browser window to no avail.

**Comment by JonReu** [comment] 2019-08-01 09:37
same here. Now I also get this error message: `Unauthorized Sandbox use detected. Your sandbox has been terminated.`
Please fix it as soon as possible, thanks!

**Comment by joram-s** [comment] 2019-08-01 11:12
Found another issue that's similar. Just for reference.
https://github.com/MicrosoftDocs/feedback/issues/1727

**Comment by JonReu** [comment] 2019-08-02 09:33
@markjulmar 
Any news?

**Comment by lkoppenol** [comment] 2019-08-02 09:59
Same problem on `store-app-data-with-azure-blob-storage`/`7-blob-uploads-and-downloads`
```
laurens_koppenol@Azure:~$ az appservice plan create --name blob-exercise-plan-laurens123 --resource-group Learn-d6225da3-75dd-4070-9921-168c54e23fa5
```
```
RequestDisallowedByPolicy - Resource 'blob-exercise-plan-laurens123' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"AppService-SKU","id":"/providers/Microsoft.Management/managementGroups/triplecrown2/providers/Microsoft.Authorization/policyAssignments/7bb64c0aa90247de8b4491c3"},"policyDefinition":{"name":"AppService-SKU","id":"/providers/Microsoft.Management/managementGroups/604c1504-c6a3-4080-81aa-b33091104187/providers/Microsoft.Authorization/policyDefinitions/e790fdfe-5672-403f-9a29-e1aa564ac680"}}]'.
```

**Comment by JonReu** [comment] 2019-08-02 11:06
@mairaw 
Unfortunately we do not get any answer! Can you help to assign to an active analyst?

**Comment by lkoppenol** [comment] 2019-08-02 11:16
i need more XP

**Comment by juanfelipebetancur** [comment] 2019-08-05 07:51
Same issue here. I also get the error message "Unauthorized Sandbox use detected. Your sandbox has been terminated" for Sandbox in this site:
https://docs.microsoft.com/en-us/learn/modules/control-azure-services-with-cli/5-exercise-create-website-using-the-cli

**Comment by nyko03** [comment] 2019-08-05 14:36
I get the same error.
`
az group list
[
  {
    "id": "/subscriptions/1b9fe108-b941-495b-aaf6-539c16640cc3/resourceGroups/Learn-578802cc-e07b-42e6-b733-c86d6bd1769e",
    "location": "westus",
    "managedBy": null,
    "name": "Learn-578802cc-e07b-42e6-b733-c86d6bd1769e",
    "properties": {
      "provisioningState": "Succeeded"
    },
    "tags": {
      "x-created-by": "freelearning",
      "x-created-for": "5443536c-a52d-4210-b87f-7a74392e597f"
    },
    "type": null
  }
]

export RESOURCE_GROUP=Learn-578802cc-e07b-42e6-b733-c86d6bd1769e
export AZURE_REGION=westus
export AZURE_APP_PLAN=popupappplan-9876543210
export AZURE_WEB_APP=popupwebapp-9876543210
az appservice plan create --name $AZURE_APP_PLAN --resource-group $RESOURCE_GROUP --location $AZURE_REGION
_**RequestDisallowedByPolicy - Resource 'popupappplan-9876543210' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"AppService-SKU","id":"/providers/Microsoft.Management/managementGroups/triplecrown2/providers/Microsoft.Authorization/policyAssignments/7bb64c0aa90247de8b4491c3"},"policyDefinition":{"name":"AppService-SKU","id":"/providers/Microsoft.Management/managementGroups/604c1504-c6a3-4080-81aa-b33091104187/providers/Microsoft.Authorization/policyDefinitions/e790fdfe-5672-403f-9a29-e1aa564ac680"}}]'.**_
`

**Comment by juanfelipebetancur** [comment] 2019-08-06 04:50
Same issue here. I also get the error message "Unauthorized Sandbox use detected. Your sandbox has been terminated" for Sandbox in this site:
https://docs.microsoft.com/en-us/learn/modules/manage-secrets-with-azure-key-vault/3-creating-vaults-storing-secrets

**Comment by joram-s** [comment] 2019-08-08 10:28
@mairaw @markjulmar 

Hi, 

I fully understand and appreciate that Microsoft developed and published the new learning journey, free of charge, to accommodate an interested public willing to learn more about Microsoft technology and its applications. 

I apply myself to learn and get certified by putting in the time, money and effort to take full advantage. However, I have put my learning journey on hold (and scheduling my exam), till I can actually practice the Azure CLI through the various modules and units. 

So, can I respectfully ask for an update on this issue (or the other related issue)? I understand if the people involved are busy, but at least something like a message that resolving this issue is not started or in progress.... anything please!

**Comment by joram-s** [comment] 2019-08-09 07:15
So after some more digging, apparently another team (or same team) is working on this issue.

Microsoft has so many channels for communication!! 
This is a twitter feed from the Docs team. https://twitter.com/docsmsft

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">⚠ Learn Sandbox update (1/2):<br><br>Over the last few weeks, Learn began to experience large-scale, persistent abuse of our Sandbox resources, which threatened to disrupt access for all Learn users. Some content remains disabled while our team works to safely restore Sandbox access.</p>&mdash; docs.microsoft.com (@docsmsft) <a href="https://twitter.com/docsmsft/status/1159615738568564737?ref_src=twsrc%5Etfw">August 9, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

and

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">(2/2) We expect to start re-enabling some affected content next week &amp; we&#39;ll post additional updates here. Thanks for your patience while we work through this.</p>&mdash; docs.microsoft.com (@docsmsft) <a href="https://twitter.com/docsmsft/status/1159615816532234241?ref_src=twsrc%5Etfw">August 9, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by joram-s** [comment] 2019-08-23 13:49
Just in case you haven't read it yet, there is an update.
https://twitter.com/docsmsft/status/1163964265117523970

Unfortunately the module I would really like to finish, doesn't work (yet). I guess I will give it another try next week or so.
https://docs.microsoft.com/en-us/learn/modules/control-azure-services-with-cli/5-exercise-create-website-using-the-cli

**Comment by Hodori88** [comment] 2019-09-03 15:59
In the other thread with a similar problem there is a post informing on the new 'appeal' functionality.
https://github.com/MicrosoftDocs/feedback/issues/1797#issuecomment-527238521

**Comment by docs-product** [comment] 2020-02-05 01:22
Duplicate of #1797

**Closed by docs-product** 2020-02-05 01:22 UTC
Labels: learn
