### ISSUE TITLE
Let me decide localization myself

### ISSUE THREAD

**Issue by AndriyGorda** [MicrosoftDocs/feedback#2103] opened 2019-10-31 10:41 UTC
Dear team,

Could you please let me stick with original en-us content?

I'm from Ukraine and your site pushes me to read Russian localized version which I don't want for multiple reasons.

The best option would be for you to massage geo-targeting the way Google search results do NOT filter out en-us content in favor of Russian.

Also let's change current "Read it in English" behavior to transfer me to original en-us page.

Currently "Read it in English" does something weird as the article itself being translated to English, but all the other content stays in Russian.

If you're not able to localize it to Ukrainian due to business reasons, then at least let me stick with original English one.

Thank you,

**Comment by sadadow** [comment] 2019-11-06 23:02
@AndriyGorda Thanks for your feedback. To better understand your issue, are you currently changing the language/local via: https://docs.microsoft.com/en-us/locale/?target=https://docs.microsoft.com/en-us/ ?

**Comment by AndriyGorda** [comment] 2019-11-07 08:12
Hello Samir,

No, I don't and don't want to bother doing it every time I go to Microsoft site from Google search results.

That's exactly my request - I shall be given the ability to stick with English starting from Google search output for docs.microsoft.com and throughout my Microsoft sites experience.

What system gives me now is:
- Only Russian localized docs.microsoft.com pages in Google search output (no English!)
- No ability to stick with English throughout Microsoft pages

**Comment by docs-product** [comment] 2019-11-16 02:26
Duplicate of #462.

**Closed by docs-product** 2019-11-16 02:26 UTC
