### ISSUE TITLE
All the azure api documentation for dotnet gives 404 errors

### ISSUE THREAD

**Issue by srobins6** [MicrosoftDocs/feedback#1425] opened 2019-04-24 21:02 UTC
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet?tabs=windows try clicking the link to https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.cloudstorageaccount.tryparse or any of the other api documentation just gives 404

**Comment by dendeli-msft** [comment] 2019-05-03 19:03
Duplicate of #1446 as it tackles the same problem.

**Closed by dendeli-msft** 2019-05-03 19:03 UTC
