### ISSUE TITLE
Link to reference source code

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#157] opened 2018-03-06 22:53 UTC
Add a link to reference source code to easily view source of current class/method

----------
⚠ Idea migrated from UserVoice

**Created By:** Giorgi D
**Created On:** 2017/04/06 20:01:40 +0000
**Votes at Migration:** 71
**Supporters at Migration:** 71

**Comment by dend** [comment] 2018-06-20 00:21
Duplicate of #433

**Closed by dend** 2018-06-20 00:21 UTC
Labels: assigned-to-pm, new-feature, triaged

**Comment by gewarren** [comment] 2024-04-04 17:24
Great news - the core .NET libraries now have links to source code!
Example: https://learn.microsoft.com/dotnet/api/system.string.chars?view=net-8.0
