### ISSUE TITLE
Language redirection

### ISSUE THREAD

**Issue by janhruby** [MicrosoftDocs/feedback#2492] opened 2020-02-12 15:50 UTC
**Describe the bug**
When browsing online documentation, browser language is always used as display language. Since reading documentation in poorly autotranslated non-english language is next to useless, it would be awesome if English would be default language of all docs and translated articles as second option. Its frustrating to scroll to bottom of every page to select usable language.

**Expected behavior**
Let English be default language and make translated (especially autotranslated) variants optional.

**Comment by docs-product** [comment] 2020-03-20 23:06
Duplicate of #462

**Closed by docs-product** 2020-03-20 23:06 UTC
