### ISSUE TITLE
Fix search and filter and library

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#29] opened 2018-03-06 22:52 UTC
A very long time ago, Microsoft documentation was great. How did this docs site get so unbelievably bad? I ran searches for "windows server 2016" backup, windows server backup, etc. and found nothing useful. All that came up was links for SQL Server backup, Active Directory, Hyper-V, security guidelines... everything EXCEPT Windows Server backup?!... The Filter box is also useless - zero results when looking at the Windows Server library. Browsing the library for Windows Server 2016 failed to give me anything about the backup also, except for a command-line reference that explains nothing about backup options... Please fix your search boxes, and also create a search screen that allows manually filtering by product name & version, other keywords, posted date, type of help/support resource etc. If I was able to do this for my websites in 1998, you can do it in 2018. I believe in you Microsoft ;)

----------
⚠ Idea migrated from UserVoice

**Created By:** Celia Ameline
**Created On:** 2018/01/31 18:02:47 +0000
**Votes at Migration:** 3
**Supporters at Migration:** 3

**Comment by dend** [comment] 2018-05-10 17:33
Duplicate of #38

**Closed by dend** 2018-05-10 17:33 UTC
