### ISSUE TITLE
Link to source from API docs

### ISSUE THREAD

**Issue by LindaLawton** [MicrosoftDocs/feedback#433] opened 2018-06-13 12:10 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice if documentation pages like [microsoft.aspnetcore.authentication.authenticationservice.challengeasync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.authenticationservice.challengeasync?view=aspnetcore-2.1) linked to their respscitve GitHub source pages  for example  [AuthenticationService.cs](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationService.cs#L85)  or at the very least link to the class or the project it self.

**Describe the solution you'd like**
I find the documentation pages lacking in what these methods actually do so find myself often checking the source code in order to understand whats going on.   Having to search for the the GitHub project can be time consuming.  It would be nice to have a link on the page.

**Describe alternatives you've considered**
1.  Just a link to the project
2. a link to the class itself.
3.  A link to the method in question.

**Additional context**

Examples on these pages would be really nice rather than just a blank description of the method.  I realize that i am asking for a lot.

**Comment by Powerhelmsman** [comment] 2018-06-13 16:10
@LindaLawton Thanks for your suggestion. I've created a internal work item to track your request. I will let you know when we have solution on it.

**Comment by Powerhelmsman** [comment] 2018-06-13 16:10
#log-suggestion @dend

**Comment by botcrane** [comment] 2018-06-13 16:10
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=25501) logged.

**Comment by mairaw** [comment] 2018-07-12 22:22
@dend should we change the title of this issue to say Link to source from API docs or something like that?

**Comment by dend** [comment] 2018-08-07 22:54
Hi folks, we've assessed this feature request and have determined that **we will not be able to address it at this time**. 

Our documentation is generated entirely from binaries (shipped in DLLs and NuGet packages), therefore there is no direct link to the source code of the product that we can re-use for the purposes of including it in our documentation. More-so, we span different versions, so while the source code is available for some, it is not for others, which will create an inconsistency in the experience.

We do have on our radar the task to implement changes that will make it easier for customers to see what NuGet package things are coming from (see #72).

**Comment by LindaLawton** [comment] 2018-08-07 23:05
Thank you for your consideration.

**Comment by dasMulli** [comment] 2019-07-31 08:09
@dend I'd very much like you to reconsider.

For the repos that stamp their binaries using SourceLink, generating a link to the source from a built product is possible. This is essentially what Visual Studio now does when debugging into NuGet or framework assemblies.

This would be a very great and useful feature and could work for any API docs for products using SourceLink.

I often use this for things like NumPy when I need to look up various implementations:
![image](https://user-images.githubusercontent.com/6129250/62194916-19666100-b37b-11e9-8969-6358ac570f22.png)

**Comment by dasMulli** [comment] 2019-07-31 08:20
@VikorHofer from what I unserstand, CoreFX now also has SourceLink via Arcade?

**Comment by ViktorHofer** [comment] 2019-08-06 23:50
Sorry was on holiday. Correct, corefx has sourcelink enabled in all customer facing assemblies.

**Comment by mairaw** [comment] 2019-09-18 18:46
@docs-product @mimig1 please look at the latest comments.

**Comment by mimig1** [comment] 2019-09-18 19:14
@mairaw - Should this go to @mimisasouvanh?

**Comment by mairaw** [comment] 2020-07-24 01:19
Apologies @mimig1 for tagging the wrong Mimi.

@BillWagner @gewarren This is related to the questions we got during our meeting today. I think we should resume this conversation again.

**Comment by gewarren** [comment] 2020-07-24 16:25
Mimi logged an [internal issue](https://dev.azure.com/ceapex/Engineering/_workitems/edit/239577/) for this in June.

**Comment by keziamicro** [comment] 2021-03-17 22:10
Hello - reviewing and cleaning up some older feedback/issues. Thanks!

**Comment by synercoder** [comment] 2021-08-11 11:02
@gewarren @keziamicro Is the internal issue closed / not further developed? Can at least 1 (this) issue stay open publicly so we know the issue is still being tracked / worked on? Because many people (including me) keep opening issues about this. My issue was closed in favor of this issue (which was reopened). But now this issue is also closed again.

Related (duplicate) issues: #2800, #2947, #157, #3099, #3416

**Comment by LindaLawton** [comment] 2021-08-11 12:48
@synercoder  I am still here and i still think this would be a valuable addition.  Just yesterday i went digging round in [ AddMicrosoftIdentityWebApi](https://github.com/AzureAD/microsoft-identity-web/blob/6b506ebb241b69dd79975b5899418af825dc1882/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs#L235)  I still had to find the link to the source myself.

As for the Developers we realize that somethings are hard to add after the fact keep thinking about it maybe something will come up one day.  See you in another three years.

**Comment by emagers** [comment] 2022-04-07 15:47
I was about to open my own issue for this same feature request before I found this one. It looks like there have been no MS updates since at least August of last year. Has anything changed on the Microsoft end at this point?

**Comment by gewarren** [comment] 2022-04-07 18:46
@emagers Yes, there has been recent activity on the internal work item. We are hoping to come up with a solution to this common request.

**Comment by LindaLawton** [comment] 2022-04-09 16:27
Well I'm still here and I still think it would be a valid addition. 

Thank you for your consideration.

**Comment by gewarren** [comment] 2024-04-04 17:03
Great news - the core .NET libraries now have links to source code! The ASP.NET Core API docs should be updated soon.
Example: https://learn.microsoft.com/en-us/dotnet/api/system.string.chars?view=net-8.0

<img width="470" alt="image" src="https://github.com/MicrosoftDocs/feedback/assets/24882762/61c6b1d7-34ec-4b36-bfa5-93833cc2e37e">

**Comment by emagers** [comment] 2024-04-04 17:34
This is really awesome news, thanks to everyone for making it happen!

**Comment by gewarren** [comment] 2024-04-09 21:32
Now that the ASP.NET Core reference docs have source links too, I'm going to close this issue.

**Closed by gewarren** 2024-04-09 21:32 UTC
Labels: enhancement, logged-request, Pri3
