### ISSUE TITLE
.Net API Browser

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#88] opened 2018-03-06 22:52 UTC
In the .Net API Browser, it would be helpful in resolving NuGet screwups if the docs show the assembly containing the namespace/API

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/11/23 10:43:23 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment] 2018-06-20 00:16
Duplicate of #72

**Closed by dend** 2018-06-20 00:16 UTC
Labels: assigned-to-pm, enhancement, triaged
