### ISSUE TITLE
"Default WPF Themes" link is incorrect

### ISSUE THREAD

**Issue by MarkIngramUK** [MicrosoftDocs/feedback#2612] opened 2020-03-25 13:53 UTC
**Describe the bug**
A link described as "Default WPF Themes" goes to a page about 2D graphics transforms.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.button?view=netframework-4.8
2. Scroll down to 'Customizing the Button Control' (https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.button?view=netframework-4.8#customizing-the-button-control)
3. Click on 'Default WPF Themes'
4. Navigates to https://github.com/Microsoft/WPF-Samples/tree/master/Graphics/2DTransforms

**Expected behavior**
To navigate to the actual 'Default WPF Themes' page, though I'm not sure what that URL is.

**Comment by mairaw** [comment] 2020-04-03 08:15
This is a duplicate of https://github.com/dotnet/dotnet-api-docs/issues/821

**Closed by mairaw** 2020-04-03 08:15 UTC
Labels: Pri3, bug, duplicate
