### ISSUE TITLE
Trouble activating Azure Sandbox in MS Learn

### ISSUE THREAD

**Issue by chethan-marideva** [MicrosoftDocs/feedback#2441] opened 2020-01-28 09:57 UTC
Hello !

I'm not able to activate the Azure sandbox environment in MS learn . I'm getting the below message when trying to activate my sandbox environment.
 
Error Message: "Unauthorized sandbox use detected. Your sandbox access has been removed.
The sandbox may only be used to complete training on Microsoft Learn. Use for any other reason is prohibited and may result in permanent loss of access to the sandbox. Please review our Terms of Use."

ScreenShot 
![image](https://user-images.githubusercontent.com/18300756/73253065-ceba8a00-41e1-11ea-9557-3c5c34aae699.png)

Please help in resolving this issue.
My MS Learn account is registered with an email: chethan.marideva@gmail.com

**Comment by mlottner** [comment] 2020-01-28 15:11
@chethan-marideva Thanks for reporting this issue. I've asked a member of our Learn team to take a look and report back on the status. 
Appreciate you taking the time to contribute to the benefit of our site and community! 
@yunyunyunyun Can you please take a look and report back to us on this issue?

**Comment by Charles1970** [comment] 2020-02-04 23:52
@yunyunyunyun  I have the same problem I start using sandbox for two days to prepare for my certificate and then I was surprised that I lost access to my sandbox, please I just want to know why I didn't do anything wrong !!

**Comment by docs-product** [comment] 2020-02-05 01:18
Duplicate of #2409

**Closed by docs-product** 2020-02-05 01:18 UTC
Labels: bug, learn
