### ISSUE TITLE
Indicate static members

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#58] opened 2018-03-06 22:52 UTC
.NET, C#
- Indicate which members are static
- Consider grouping of of static/non-static members

----------
⚠ Idea migrated from UserVoice

**Created By:** dev
**Created On:** 2017/12/13 11:36:39 +0000
**Votes at Migration:** 7
**Supporters at Migration:** 7

**Comment by dend** [comment] 2018-06-20 00:07
#log-suggestion @dend

**Comment by botcrane** [comment] 2018-06-20 00:08
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=25942) logged.

**Comment by dend** [comment] 2018-08-21 23:35
Duplicate of #469

**Closed by dend** 2018-08-21 23:35 UTC
Labels: assigned-to-pm, enhancement, logged-request
