### ISSUE TITLE
Not showing english content by default is kinda annoying

### ISSUE THREAD

**Issue by Xawx** [MicrosoftDocs/feedback#2605] opened 2020-03-22 15:07 UTC
**Link to article:**
https://docs.microsoft.com/pl-pl/dotnet/csharp/language-reference/keywords/for

**Problem:**

When I'm trying to find something in ms docs I'm typing some keywords into Google

e.g I'm curious about `C#'s for loop` I'm typing `C# for loop` and clicking first link which leads to `MSDocs`, but it by default shows me content in `pl-pl` language

But the problems is that I always have to change in url's `pl-pl` to `en-us`  or use switch button (which isn't always there)

But actually why?

English content not only almost always has way higher quality, then it also contains `untranslateable` words which are programming specific and do not make sense or arent commonly used in other languages

Of course I'm aware that there are people who'd want to see contant in their own language, so the option to switch to other lang should be still avaliable, but I bet that decent majority of people would rather see docs in english due to above mentioned reasons.

It's seriously annoying to having to switch lang basically `everyday * x times` 

I strongly believe that anyone who's somewhat serious about programming will have no problem with English by default because it's insanely difficult to do anything programming related without english (if you want to work with with other people from around the world, then you've no choice)

Also I tend to believe that not using english by default in Visual Studio makes it harder for people to learn C# because it's relatively very difficult to find answers | tips while dealing with particular error because search engine (Google) is full of english versions. Basically you cannot just copy paste into Google your error in other lang than english and expect this search to be at least similarly successful to english one.

**Comment by flamaniac** [comment] 2020-03-24 22:35
YEP. Auto translating docs is the most STUPID solution I have ever seen.... And you didn't fixed that for so long. WTF?

**Comment by DhiaBakreen** [comment] 2020-03-25 01:20
Thank you for creating the issue[top](https://www.topvideo-tv.com/)

**Comment by JasonCard** [comment] 2020-03-27 00:14
@bodhigautam Could you please help to update on this?

**Comment by srvbpigh** [comment] 2020-04-03 08:37
Hello, @Xawx
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by bodhigautam** [comment] 2020-04-03 17:06
@Xawx  , you can always enable Toggle on the top right corner. Enabling this will enable the content will always appear in English, no matter which page you go. We store the users toggle choice across multiple sessions.
![image](https://user-images.githubusercontent.com/41086513/78386384-55993380-7592-11ea-82eb-e04d829bdcee.png)
@dend Here is another request where user wants to get redirected to English always no matter on which language they are.

**Comment by docs-product** [comment] 2020-04-08 00:19
Duplicate of #462

**Closed by docs-product** 2020-04-08 00:19 UTC
Labels: Pri3, loc
