### ISSUE TITLE
Typo in AssertQubitState article

### ISSUE THREAD

**Issue by nthalpy** [MicrosoftDocs/feedback#482] opened 2018-07-03 23:10 UTC
I think there is a typo at example of AssertQubitState article (https://docs.microsoft.com/en-us/qsharp/api/prelude/microsoft.quantum.extensions.testing.assertqubitstate?view=qsharp-preview).

Original example says
```
using (qubits = Qubit[2]) {
    Y(qubits[1]);
    // |0〉: a=(1 + 0*i), b=(0 + 0*i)
    AssertQubitState(((1., 0.), (0., 0.)), qubits[0], 1e-5);
    // Y |0〉 = i |1〉: a=(0 + 0*i), b=(0 + 1*i)
    AssertQubitState(((0., 0.), (0., 1.)), qubits[0], 1e-5);
}
``` 
but `Y|0>` is `qubits[1]`, not `qubits[0]`.

So I think the example should change to
```
using (qubits = Qubit[2]) {
    Y(qubits[1]);
    // |0〉: a=(1 + 0*i), b=(0 + 0*i)
    AssertQubitState(((1., 0.), (0., 0.)), qubits[0], 1e-5);
    // Y |0〉 = i |1〉: a=(0 + 0*i), b=(0 + 1*i)
    AssertQubitState(((0., 0.), (0., 1.)), qubits[1], 1e-5);
}
```

**Comment by nthalpy** [comment] 2018-07-04 13:37
Additionally, I found that code
```
using (qubits = Qubit[2]) {
    Y(qubits[1]);
    // |0〉: a=(1 + 0*i), b=(0 + 0*i)
    AssertQubitState(((1., 0.), (0., 0.)), qubits[0], 1e-5);
    // Y |0〉 = i |1〉: a=(0 + 0*i), b=(0 + 1*i)
    AssertQubitState(((0., 0.), (0., 1.)), qubits[1], 1e-5);
}
```
makes compiler error 
```
QS0001	expected type Microsoft.Quantum.Extensions.Math.Complex, instead got type (Double, Double)
```
and
```
QS0001	Type mismatch for argument: (Microsoft.Quantum.Extensions.Math.Complex, Microsoft.Quantum.Extensions.Math.Complex) expected, but ((Double, Double), (Double, Double)) was provided
```

I think we should convert `(Double, Double)` to `Complex`, so code will be like
```
using (qubits = Qubit[2]) {
    Y(qubits[1]);
    // |0〉: a=(1 + 0*i), b=(0 + 0*i)
    AssertQubitState((Complex(1., 0.), Complex(0., 0.)), qubits[0], 1e-5);
    // Y |0〉 = i |1〉: a=(0 + 0*i), b=(0 + 1*i)
    AssertQubitState((Complex(0., 0.), Complex(0., 1.)), qubits[1], 1e-5);
}
```

**Comment by Powerhelmsman** [comment] 2018-07-05 17:22
@alan-geller Can you also take a look at this issue?

**Comment by alan-geller** [comment] 2018-07-11 20:59
I'll take a look.

**Comment by alan-geller** [comment] 2018-08-13 22:33
I've created a bug in our internal system to track this. It might not get fixed for a little while because this page is autogenerated and goes through a publishing pipeline, and I'm not sure how frequently we push.

**Comment by alan-geller** [comment] 2018-08-15 22:00
Fixed in https://github.com/MicrosoftDocs/quantum-docs-pr/pull/283. I also fixed the source doc comment so that this won't reappear next time we publish from source.

**Comment by Powerhelmsman** [comment] 2018-08-15 22:11
@nthalpy Just let you know. The issue is resolved

**Closed by Powerhelmsman** 2018-08-15 22:11 UTC
Labels: content, resolved
