### ISSUE TITLE
VSTS REST API List Iterations does not accept 'past' or 'current' values for $timeframe

### ISSUE THREAD

**Issue by stuntbeaver** [MicrosoftDocs/feedback#445] opened 2018-06-20 01:40 UTC
Using the VSTS REST api version 4.1 AND 5.0 preview 1, making a GET request to list iterations using the $timeframe query parameter works when supplying 'current' as a timeframe value, but does not work when using 'past' or 'future' as per the documentation.

**To Reproduce**
Make a get request using the following URL (fill in appropriate values):
`https://{CompanyName}.visualstudio.com/{ProjectName}/_apis/work/teamsettings/iterations?$timeframe=past&api-version=4.1`

This returns:
```
{
    "$id": "1",
    "innerException": null,
    "message": "Specified argument was out of the range of valid values.\r\nParameter name: timeframe",
    "typeName": "System.ArgumentOutOfRangeException, mscorlib",
    "typeKey": "ArgumentOutOfRangeException",
    "errorCode": 0,
    "eventId": 0
}
```

Using either $timeframe=past or $timeframe=future reproduces the fault.
Using $timeframe=current works fine.

**Expected behaviour**
Using 'past' and 'future' as defined in the documentation here https://docs.microsoft.com/en-us/rest/api/vsts/work/iterations/list?view=vsts-rest-4.1 and https://docs.microsoft.com/en-us/rest/api/vsts/work/iterations/list?view=vsts-rest-5.0 should return a list of past and future iterations.

**Desktop (please complete the following information):**
n/a.

**Smartphone (please complete the following information):**
n/a

**Additional context**
Reproduced in Postman and C#, .Net framework 4.7.2 console application using NuGet package RestSharp v106.2.2.

**Comment by hellosnow** [comment] 2018-06-20 04:20
@tedchamb could you please help to take a look?

**Comment by hellosnow** [comment] 2018-06-21 02:52
Transfer to an issue of https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/52, so that @wnjenkin can triage.

**Comment by Powerhelmsman** [comment] 2018-06-21 05:02
@hellosnow Is MicrosoftDocs/vsts-rest-api-specs public? So user can be informed when the issue is resolved? If not, I prefer @wnjenkin assign the issue here.

**Comment by wnjenkin** [comment] 2018-06-21 14:14
@Powerhelmsman yes it is public

**Comment by Powerhelmsman** [comment] 2018-06-21 16:53
@stuntbeaver Your issue is transferred to MicrosoftDocs/vsts-rest-api-specs#52. @wnjenkin will help you there. I will close this issue in this repo now. Let me know if have other question so we can reopen it and continue the discussion.

**Closed by Powerhelmsman** 2018-06-21 16:53 UTC
Labels: assigned-to-pm, triaged

**Comment by hellosnow** [comment] 2018-06-28 03:44
@stuntbeaver refer to https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/52, this issue has been resolved. The descriptions has been updated to show only current is supported. Hope it works for you.
