### ISSUE TITLE
Link to NuGet packages

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#121] opened 2018-03-06 22:53 UTC
If someone is reading documentation about a class, namespace or assembly it would be great if the corresponding NuGet package is linked if available.

----------
⚠ Idea migrated from UserVoice

**Created By:** Saqib Javed
**Created On:** 2017/08/17 12:48:40 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment] 2018-06-20 00:16
Duplicate of #72

**Closed by dend** 2018-06-20 00:16 UTC
Labels: assigned-to-pm, new-feature, triaged
