### ISSUE TITLE
Add ASP.NET MVC and WebAPI API reference

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#90] opened 2018-03-06 22:52 UTC
The API reference for MVC and WebAPI is still only available on MSDN, not on the "docs" site.

https://docs.microsoft.com/en-us/aspnet/api-ref

Ideally, they should also be integrated into the API Browser.

----------
⚠ Idea migrated from UserVoice

**Created By:** Richard
**Created On:** 2017/11/20 15:51:06 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment] 2018-05-17 18:34
@Rick-Anderson @danroth27 are there any plans to move those over?

**Comment by Rick-Anderson** [comment] 2018-05-17 18:53
I think these will be moved but maybe not to [API Browser](https://docs.microsoft.com/en-us/dotnet/api/) right away.

@mschulz-msft is [ASP.NET MVC 4 Reference](https://msdn.microsoft.com/en-us/library/gg416515(v=vs.108).aspx) and
[ASP.NET Web API Reference](https://msdn.microsoft.com/en-us/library/hh849329(v=vs.108).aspx) being moved.

**Comment by Powerhelmsman** [comment] 2018-05-24 23:46
@mschulz-msft Can you answer the question from Rick?

**Comment by dend** [comment] 2018-06-21 00:03
If that is managed reference, we need to make sure we integrate it in the API Browser.

@danroth27 @Rick-Anderson do you know where we can get the NuGet packages/assemblies for the above?

cc: @mschulz-msft

**Comment by dougbu** [comment] 2018-06-21 16:05
The list of ASP.NET packages we have recently updated is:
- Microsoft.AspNet.Cors v5.2.6
- Microsoft.AspNet.Mvc v5.2.6
- Microsoft.AspNet.Razor v3.2.6
- Microsoft.AspNet.WebApi v5.2.6
- Microsoft.AspNet.WebApi.Client v5.2.6
- Microsoft.AspNet.WebApi.Core v5.2.6
- Microsoft.AspNet.WebApi.Cors v5.2.6
- Microsoft.AspNet.WebApi.HelpPage v5.2.6
- Microsoft.AspNet.WebApi.Owin v5.2.6
- Microsoft.AspNet.WebApi.OwinSelfHost v5.2.6
- Microsoft.AspNet.WebApi.SelfHost v5.2.6
- Microsoft.AspNet.WebApi.Tracing v5.2.6
- Microsoft.AspNet.WebApi.WebHost v5.2.6
- Microsoft.AspNet.WebPages v3.2.6
- Microsoft.AspNet.WebPages.Data v3.2.6
- Microsoft.AspNet.WebPages.OAuth v3.2.6
- Microsoft.AspNet.WebPages.WebData v3.2.6
- Microsoft.AspNet.WebPages v3.2.6
- MvcDiagnostics v5.2.6

Not sure if it matters in this context, but we've updated locale-specific packages for all of the above that have them.

**Comment by dend** [comment] 2018-06-21 16:20
@danroth27 @dougbu thanks, this looks good. Should all these be classified as "ASP.NET MVC5"?

**Comment by danroth27** [comment] 2018-06-21 22:59
These are collectively the packages for ASP.NET MVC, Web API and Web Pages. They typically all ship together but they are separate frameworks with separate versions. We should probably spit them.

**ASP.NET MVC 5.2**
Microsoft.AspNet.Mvc v5.2.6
MvcDiagnostics v5.2.6

**ASP.NET Web Pages 3.2**
Microsoft.AspNet.WebPages v3.2.6
Microsoft.AspNet.WebPages.Data v3.2.6
Microsoft.AspNet.WebPages.OAuth v3.2.6
Microsoft.AspNet.WebPages.WebData v3.2.6
Microsoft.AspNet.WebPages v3.2.6
Microsoft.AspNet.Razor v3.2.6

**ASP.NET Web API 5.2**
Microsoft.AspNet.WebApi v5.2.6
Microsoft.AspNet.WebApi.Client v5.2.6
Microsoft.AspNet.WebApi.Core v5.2.6
Microsoft.AspNet.WebApi.Cors v5.2.6
Microsoft.AspNet.WebApi.HelpPage v5.2.6
Microsoft.AspNet.WebApi.Owin v5.2.6
Microsoft.AspNet.WebApi.OwinSelfHost v5.2.6
Microsoft.AspNet.WebApi.SelfHost v5.2.6
Microsoft.AspNet.WebApi.Tracing v5.2.6
Microsoft.AspNet.WebApi.WebHost v5.2.6
Microsoft.AspNet.Cors v5.2.6

**Comment by mschulz-msft** [comment] 2018-06-22 15:39
Sorry for the late response, somehow this just hit my inbox. 

We moved some ASP.NET docs from MSDN to docs.microsoft.com/previous-versions as part of the migration project. The migrated content can be found here: https://docs.microsoft.com/en-us/previous-versions/aspnet/

If there is other content not captured in the above and still on MSDN, we need to add it to the backlog for the move ASAP.

**Comment by dend** [comment] 2018-06-22 17:19
@danroth27 great, thanks! This should give us a starting point.

**Comment by Powerhelmsman** [comment] 2018-06-27 22:15
The issue is transferred to vsts-rest-api team. They will help there. I will close as transferred. If you have other question related to this issue, we can reopen it and continue discussion.

**Comment by dend** [comment] 2018-06-29 01:43
@Powerhelmsman this is not REST. This is a request to onboard .NET-based APIs to docs.microsoft.com. I will take care of this and close the issue once we have the APIs onboarded.

**Comment by dend** [comment] 2018-08-31 21:31
A good chunk of the ASP.NET MVC content is in this PR: https://github.com/aspnet/ApiDocs/pull/81/. We will continue working on shipping the rest soon.

**Comment by dend** [comment] 2018-10-31 03:59
The content is now available:
https://docs.microsoft.com/en-us/dotnet/api/System.Web.Helpers?view=aspnet-webpages-3.2

**Closed by dend** 2018-10-31 03:59 UTC
Labels: content, in-progress

**Comment by danroth27** [comment] 2018-10-31 20:09
Thanks @dend!

Did the ASP.NET Web API docs get added? I only see MVC and Web Pages listed . . .

![image](https://user-images.githubusercontent.com/1874516/47815658-30a1f080-dd0e-11e8-890e-020f159f5e57.png)
