### ISSUE TITLE
Look & Feel

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#449] opened 2018-06-21 16:00 UTC
Original issue from https://github.com/dotnet/docs/issues/6078 by @MuraliManickam

Hi Team, This documentation UI looks great! but add on the read mode kind of feature will help the user focus on the content clearly. It would be great if you remove the side navigation bar on both left & right on reading mode. Thanks!

**Comment by dend** [comment] 2018-06-21 16:20
@dastaffo is the right PM for this ask :)

**Comment by dend** [comment] 2018-07-04 20:49
Duplicate of #97, so closing this entry.

**Closed by dend** 2018-07-04 20:49 UTC
Labels: enhancement
