### ISSUE TITLE
Stop translating to Dutch - It's useless and nobody uses it

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#21] opened 2018-03-06 22:52 UTC
Stop translating to Dutch at all. Use people to translate or don't translate at all. No machine translation, its useless for Dutch. And the suggestion of Den Delimarsky to submit feedback on the page where it happens is also useless. The complete document need to rewritten. Every document.

----------
⚠ Idea migrated from UserVoice

**Created By:** Randolf
**Created On:** 2018/02/23 10:42:27 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment] 2018-03-07 17:11
Duplicate of #23

**Closed by dend** 2018-03-07 17:11 UTC
