### ISSUE TITLE
Sandbox issue in Microsoft Azure Learning Path

### ISSUE THREAD

**Issue by noxouille** [MicrosoftDocs/feedback#2439] opened 2020-01-27 18:58 UTC
**Describe the bug**
Error of "Unauthorized sandbox used" appear when attempting to complete Microsoft Azure Learning path that requires sandbox. My Microsoft account is newly created, and I did not do anything that violates the use of sandbox. There are no other explanations why the error occurs. 
(EDIT)
My Microsoft account is ferdi.pratama.phd@outlook.com

**To Reproduce**
1. Go to Microsoft Azure Learning Path that requires Sandbox (e.g., Azure fundamentals exercise, Create a website in Azure)
2. Click on Activate Sandbox
3. See error as shown in the screenshot attached

**Expected behavior**
I am expected to be able to use the sandbox.

**Screenshots**
![error](https://user-images.githubusercontent.com/1827216/73204127-71a0d480-410c-11ea-8dc9-c8bd4b9fd622.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser chrome
 - Version 79.0.3945

**Comment by mlottner** [comment] 2020-01-28 15:24
@noxouille Thanks for reporting this issue. I've asked a member of our Learn team to take a look and report back on the status.
Appreciate you taking the time to contribute to the benefit of our site and community!
@yunyunyunyun Can you please take a look and report back to us on this issue?

**Comment by noxouille** [comment] 2020-02-03 20:38
Any updates so far? @mlottner @yunyunyunyun

**Comment by Charles1970** [comment] 2020-02-04 23:55
@mlottner  please I have the same issues and I'm sure I didn't do anything wrong I'm just using sandbox to prepare for my azure certificate can you please fix that for me

**Comment by docs-product** [comment] 2020-02-05 01:18
Duplicate of #2409

**Closed by docs-product** 2020-02-05 01:18 UTC
Labels: bug, learn
