### ISSUE TITLE
System.IO.FileInfo wrong path

### ISSUE THREAD

**Issue by bencoskater** [MicrosoftDocs/feedback#751] opened 2018-10-09 22:03 UTC
Hi,

**Describe the bug**
FileInfo provides wrong path to the file.

**To Reproduce**
1. Create a dotnet core console 2.1 or 2.2 preview 2 (the result is the same)
2. Instanciate a new FileInfo with the full path to a file
3. Put a breakpoint after the instantiation and Run in debug
Instead of getting the path to the file, FileInfo concatenate the folder path of the application with the path provided in the instance...

**Expected behavior**
Must have the path to the provided path

**Screenshots**
<img width="530" alt="wrongpath" src="https://user-images.githubusercontent.com/6197198/46701359-77a83480-cbed-11e8-8fa4-28cf74328a37.png">

**Desktop (please complete the following information):**
 - Windows 10
 - Core 2.2 preview 2 (same behavior on 2.1)

What's wront?

Thanks

**Comment by EdisonDa** [comment] 2018-10-10 05:15
@bencoskater could you provide me the docs link?

**Comment by bencoskater** [comment] 2018-10-10 11:10
Hi,

Here it is: https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo?view=netframework-4.7.2

**Comment by EdisonDa** [comment] 2018-10-10 12:06
@bencoskater Looks is not like a documentation issues. I suggest you can try in some other environment? I also get the expected result with .net core 2.1. 
![image](https://user-images.githubusercontent.com/10289595/46735122-e22da300-ccc7-11e8-828d-d81888fda862.png)

Would you mind me to close this one?

**Comment by bencoskater** [comment] 2018-10-10 12:41
Oh, it’s a git only related to documentation, right?

**Comment by svick** [comment] 2018-10-10 15:40
@bencoskater Yes, this GitHub repository is about .Net documentation. 

Though I also can't reproduce your issue. Does it work if you use backslashes instead of slashes? Is it possible that the path string contains some invisible characters?

**Comment by bencoskater** [comment] 2018-10-10 15:49
Ok, I thought it was for bug reports. Yes I used backslashes before trying slashes.
The path is a copy/paste from windows, there is only space. I noticed the bug occurred in the using statement of my DB context, it seems dotnet core is confused between System.IO.FileInfo and my model VStream.Data.FileInfo. I renamed my model and I am using methods from Path and File classes. Please close the ticket, I will try later the GileInfo and if it’s still present I will open a ticket on the good git.

Thanks

**Closed** 2018-10-11 00:54 UTC
Labels: question
