### ISSUE TITLE
Banned?

### ISSUE THREAD

**Issue by VitalyBruk** [MicrosoftDocs/feedback#1707] opened 2019-07-08 19:09 UTC
Why I get **Your account does not have access to the forums system** message on https://social.technet.microsoft.com/Forums/en-us/home login?

Profile
https://social.technet.microsoft.com/profile/vitalybruk/

What I did wrong?

**Comment by ryanmajidi** [comment] 2019-07-08 21:43
@saldana Can you please take a look at this issue?

**Comment by saldana** [comment] 2019-07-08 21:50
@VitalyBruk can you provide more information on when  you get such message? The forums are accessible anonymously, and you only need an account when you are trying to do a write action on the site, such as ask a question, provide an answer, vote, etc.

**Comment by VitalyBruk** [comment] 2019-07-09 07:54
Thanks @saldana 
I want to write action on the forums and be a useful part of the community.
Two days ao I did log in for the first time, day after that - already get that message: **Your account does not have access to the forums**. I do not know what I did wrong and why it is so ...

My profile:
https://social.msdn.microsoft.com/profile/vitalybruk/
or
https://social.technet.microsoft.com/profile/vitalybruk/

Links:
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/home
https://social.technet.microsoft.com/forums/en-us/home

Screen Shots:
![social technet2](https://user-images.githubusercontent.com/52676359/60869616-f511db80-a237-11e9-90c0-45d77899a52b.PNG)

![social technet](https://user-images.githubusercontent.com/52676359/60869021-e0811380-a236-11e9-9e8e-4394012d2a9a.PNG)

**Comment by saldana** [comment] 2019-07-10 02:29
We appreciate your willingness to participate in the forums @VitalyBruk. I have sent a mail to my support team asking them why see the error below. You should not see that for us. Thanks a lot for the additional information and screenshot. I will come back to you as soon as my support team investigates this further. Thank you.

**Comment by saldana** [comment] 2019-07-10 22:55
@VitalyBruk can you check again and let us know if the issue is resolved now? Sorry about the trouble.

**Comment by VitalyBruk** [comment] 2019-07-12 10:46
Thank you @saldana !
Look great, thanks!
Very appreciate it!!

**Comment by saldana** [comment] 2019-07-15 02:25
Great, closing the issue then!

**Closed by saldana** 2019-07-15 02:25 UTC
