### ISSUE TITLE
Improve output of search function

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#57] opened 2018-03-06 22:52 UTC
Example: I'm searching for "System.Windows.application class" on the right top of the window in the .NET context.
None of the output results on the first result page contains the word "class".
The UI doesn't show what the sort order is (where the order is based on).  Can you add an order menu with e.g. the following options: relevancy, modifcation date, most popular (most requested), ...
Can you add an option to group output?
Can you add filters that can be applied recursively: you start with a broad search and add filter to the search results as you go
Filters could have e.g. the following filter parameters:
application (e.g. Visual Studio), Technology (e.g. ".NET", "Azure", ..). Version (for filter elements where applicable e.g. to be able to filter on .NET 4.5.1), language (e.g. VB, C#, C++)

----------
⚠ Idea migrated from UserVoice

**Created By:** Dirk Jan D.
**Created On:** 2017/12/14 10:31:03 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment] 2018-03-07 02:03
@presleyy tagging you here for search, and myself for .NET content.

**Comment by presleyy** [comment] 2018-03-28 08:25
@dend #55 is related. The .NET API browser search will return better results for the case of #55. Specific scope and later the feature of adding filters with facets will also improve the search results relevance. Continue investigating it.

**Comment by dend** [comment] 2018-03-28 17:26
I think the ask boils down to us having filters in search. I believe for APIB we already have some plans for improvements.

**Comment by presleyy** [comment] 2018-03-29 02:50
Yes, having filters in search is a feature in design phase.

**Comment by dend** [comment] 2018-06-20 00:04
**Update:** This issue will be resolved once search filters are implemented. cc: @presleyy

**Comment by dend** [comment] 2018-07-12 22:08
Duplicate of #50

**Closed by dend** 2018-07-12 22:08 UTC
Labels: assigned-to-pm, enhancement
