### ISSUE TITLE
Allow users to have a preferred language (especially en-us)

### ISSUE THREAD

**Issue by HenryJammes** [MicrosoftDocs/feedback#2643] opened 2020-04-03 10:19 UTC
**Is your feature request related to a problem? Please describe.**
I use docs content extensively and search for it using search engines, such as Bing or Google.
Even though I use English strings to look for content, results are often localized pages of docs (fr-fr) because of my user context. This is really painful because I want the original content to be displayed, in en-us locale.

**Describe the solution you'd like**
I would like the browser (in a cookie?) to remember that I prefer en-us content and to always defaults to that language, even if I open a fr-fr page from search engine, so that I no longer have to manually change the language.
Same for pages without the locale part of the URL, I want them to default to en-us and not fr-fr.
This could also be profile setting as well, although I find that I'm rarely logged in.

**Describe alternatives you've considered**
I manually have to change the URL to revert to "en-us" for the original content, or have to use the "change language" option (that's a bit more cumbersome).
I don't want to fully change my client context to en-us because the rest of the time, I'm indeed looking for localized content. Just not on docs.

**Comment by docs-product** [comment] 2020-04-08 00:18
Duplicate of #462

**Closed by docs-product** 2020-04-08 00:18 UTC
Labels: Pri3, enhancement
