### ISSUE TITLE
unable to activate sandbox

### ISSUE THREAD

**Issue by mftpr** [MicrosoftDocs/feedback#2417] opened 2020-01-22 16:26 UTC
**Problem**:
Created a microsoft learn account just yesterday and started to do the Azure Foundations but got stuck in https://docs.microsoft.com/en-us/learn/modules/welcome-to-azure/4-exercise-create-website as the sandbox can't get activated. Only receiving the following error message, tried again today, same issue.

> Unauthorized sandbox use detected. Your sandbox access has been removed.
> 
> The sandbox may only be used to complete training on Microsoft Learn. Use for any other reason is prohibited, and may result in permanent loss of access to the sandbox. Please review our Terms of Use.

**Comment by mlottner** [comment] 2020-01-28 15:42
@mftpr  Thanks for reporting this issue. I've asked a member of our Learn team to take a look and report back on the status.
Appreciate you taking the time to contribute to the benefit of our site and community!
@yunyunyunyun Can you please take a look and report back to us on this issue?

**Comment by mftpr** [comment] 2020-02-02 15:03
The issue persists, seems also to be reported multiple times, found a few duplicates.

Today login was possible but the sandbox has no subscription attached to it, and adding one is not possible. Directly after login to the sandbox one receives an error and adding a subscription in the sandbox isn't working.

Given that using the sandbox is a requirement for that learn step to mark complete this is still an issue.

**Comment by docs-product** [comment] 2020-02-05 01:19
Duplicate of #2409

**Closed by docs-product** 2020-02-05 01:19 UTC
Labels: bug, learn
