### ISSUE TITLE
Allow to dynamically hide the panels on the left and right

### ISSUE THREAD

**Issue by fkleiner** [MicrosoftDocs/feedback#2001] opened 2019-10-05 21:08 UTC
**Is your feature request related to a problem? Please describe.**
When reading Docs articles on my iPad, a large part of the screen is wasted by the left (navigation) and right ("Is this page useful?") panels.

**Describe the solution you'd like**
I would like to be able to dynamically hide one or both of the panels when reading an article (e.g., by clicking a small arrow).

**Describe alternatives you've considered**
I currently use reading mode on the iPad.

**Comment by mairaw** [comment] 2019-10-10 04:22
Thanks for your feedback. Closing as a duplicate of #167.

**Closed by mairaw** 2019-10-10 04:22 UTC
