### ISSUE TITLE
Please let me know if there is there a limit of REST API actions(create, update, delete) for subscriptions?  Using either REST API directly or azure cli. I couldn't find that info in the docs.

### ISSUE THREAD

**Issue by mosolano** [MicrosoftDocs/feedback#3381] opened 2021-01-13 17:17 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mosolano** [comment] 2021-01-13 17:19
https://docs.microsoft.com/en-us/rest/api/searchservice/addupdate-or-delete-documents

https://docs.microsoft.com/en-us/rest/api/azure/

**Comment by gewarren** [comment] 2021-01-15 02:21
@HeidiSteen Could you look at this issue?

**Comment by HeidiSteen** [comment] 2021-01-15 05:04
Thanks @gewarren for the heads up about this issue!  @mosolano, there are no limits on the number of requests you can send.  All of the subscription service limits are documented in this article:  https://docs.microsoft.com/en-us/azure/search/search-limits-quotas-capacity 

Please reply back if this doc doesn't answer your question.  If you believe your issue is addressed, could you please close the issue? 

Thanks for reaching out with your question.

**Comment by JasonWHowell** [comment] 2021-01-23 00:20
Feel free to reopen if the issue isn't resolved. 
#please-close

**Closed by JasonWHowell** 2021-01-23 00:20 UTC
Labels: Pri3, enhancement
