### ISSUE TITLE
https://docs.microsoft.com/en-us/partner-center/recon-file-charge-types 

### ISSUE THREAD

**Issue by v-sashig** [MicrosoftDocs/feedback#3475] opened 2021-02-12 05:10 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gewarren** [comment] 2021-02-12 21:26
Dupe of 3476?

**Closed by gewarren** 2021-02-12 21:26 UTC
Labels: Pri3, enhancement
