### ISSUE TITLE
WTF All Google Links are broken due to new MSDN API redirect

### ISSUE THREAD

**Issue by frevds** [MicrosoftDocs/feedback#526] opened 2018-07-16 22:28 UTC
I'm searching for some API member on Google, e.g. "SharePoint SPList members", clicking the first result to https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.splist_members.aspx and end up at https://docs.microsoft.com/en-us/dotnet/api/?redirectedfrom=MSDN, no matter what I search for, so I have to type that there again. What a retarded annoyance, if you introduce a new API browser you shouldn't p*** off people like that. Is it to much to ask to include the damn origin and present search results in your new chic search? Like this totally pointless.  I had already found the right page (and Google is MUCH much better at finding out what I actually want to find), now I have to find it all over again and end up at pages that have not the same relevance. Then I cannot even find what I'm looking for, because the browser shows me results for .NET C++ only, so I have to setup tags now or what? It's much easier for me to browse the web archive. Discard that crappy solution and bring back the old MSDN, please.

**Comment by nschonni** [comment] 2018-07-16 22:37
Duplicate of #517

**Comment by parthrawal** [comment] 2018-07-17 07:56
Totally Agree. Such a Stupid implementation from MS. Not expecting such a work from MS. I think we should put it on Twitter or something

**Comment by Powerhelmsman** [comment] 2018-07-20 17:54
@frevds This bug is duplicated with #517. I will close this issue and track the status there

**Closed by Powerhelmsman** 2018-07-20 17:54 UTC
Labels: bug, duplicate
