### ISSUE TITLE
System.Numerics Namespace description

### ISSUE THREAD

**Issue by MartyIX** [MicrosoftDocs/feedback#2912] opened 2020-07-01 06:43 UTC
Hi,

on page https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-3.1, you can see:

![image](https://user-images.githubusercontent.com/203266/86211515-ce4e6280-bb76-11ea-8355-a21d87b25e7d.png)

There are commas but no text between the commas.

Cheers

PS: Also here:

![image](https://user-images.githubusercontent.com/203266/86212283-086c3400-bb78-11ea-8529-4784b34bebbe.png)

**Comment by mairaw** [comment] 2020-07-03 01:55
Thanks for your feedback. This is a known issue.

Duplicate of #637

/cc @mimisasouvanh

**Closed by mairaw** 2020-07-03 01:55 UTC
Labels: Pri3, bug
