### ISSUE TITLE
When selecting VB code, mainly C++ code shows

### ISSUE THREAD

**Issue by brewmanz** [MicrosoftDocs/feedback#1325] opened 2019-03-26 00:06 UTC
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.
Note that, having signed in,  the the word 'comment' does not exist on this page, and the 'Is this page helpful?' (usually at the bottom) does not show.

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.textrenderer.measuretext?view=netframework-4.7.2

**Problem:**
Having select "VB", about half of the code samples are in C++ (the rest are in VB)

**Comment by mairaw** [comment] 2019-04-03 06:37
Thanks for your feedback @brewmanz.

@sudeepku @dendeli-msft  
This one should be assigned to @joelmartinez or closed as duplicate of https://github.com/mono/api-doc-tools/issues/356. I don't have permissions to do this.

**Comment by mairaw** [comment] 2019-06-11 06:04
@sudeepku @dendeli-msft ping

**Comment by mairaw** [comment] 2019-06-17 17:43
Closing this one as a duplicate of https://github.com/mono/api-doc-tools/issues/356, since what's missing in this page is the VB signatures.

**Closed by mairaw** 2019-06-17 17:43 UTC
Labels: content, duplicate
