### ISSUE TITLE
 unable to activate the sandbox 

### ISSUE THREAD

**Issue by burmoh12** [MicrosoftDocs/feedback#2409] opened 2020-01-20 20:32 UTC
*I recently started one of the tutorials on Microsoft Learn (https://docs.microsoft.com/en-us/learn/modules/create-azure-storage-account/) and when I got to step 5, where a sandbox account is required, I was unable to activate the sandbox and was told that the reason was "Unauthorized sandbox use detected" and I can not  appeal the issue. I have seen other people who are having since the Nov of last year when this Bug will be fixed if it is not I do not know what I have done wrong 
Plead I need some input to the issue as I need to continue on my training I planning to the exam as soon as i am done with full training please help

**Comment by docs-product** [comment] 2020-02-05 01:21
Duplicate of #1797

**Closed by docs-product** 2020-02-05 01:21 UTC
Labels: assigned-to-pm, bug
