### ISSUE TITLE
The generalize() API of Python SDK does not work for Windows VM

### ISSUE THREAD

**Issue by atishbits** [MicrosoftDocs/feedback#486] opened 2018-07-05 09:33 UTC
Hi
The Azure Python SDK [generalize](https://docs.microsoft.com/en-us/python/api/azure.mgmt.compute.v2017_03_30.operations.virtualmachinesoperations?view=azure-python#generalize)() API for VirtualMachineOperations in Compute Client does not "sysprep" the VM. Instead, one must leverage the CustomerScriptsExtension to perform Sysprep on the VM before capturing its image. Curious what is the intended purpose of generalize API, and why it does not result in Sysprep of Windows VM?
Thanks

**Comment by dend** [comment] 2018-07-05 19:31
@lmazuel can you please help address this item?

**Comment by lmazuel** [comment] 2018-07-06 00:05
Duplicate of https://github.com/Azure-Samples/virtual-machines-python-manage/issues/18

This is a RestAPI question and has nothing to do with Python:
- We should raise to Compute team
- @yugangw-msft might know part of his work in the CLI team on Compute

**Comment by dend** [comment] 2018-07-06 00:20
Closing this issue as a duplicate.

**Closed by dend** 2018-07-06 00:20 UTC
Labels: assigned-to-pm
