### ISSUE TITLE
Search rarely finds the topic requested

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#111] opened 2018-03-06 22:52 UTC
If you use the search in the top right corner, even with focused scope, it rarely actually finds what you wanted to search for. Instead it finds all the references to said topic.  Examples

.NET - INotifyPropertyChanged => Finds examples of how to implement it but not the interface itself
.NET - IValidatableObject => Doesn't find anything related to the interface
.NET - Validator class => Nothing

The fastest way to find things is to go to google and type "C# docs topic" and then filter out the msdn links

----------
⚠ Idea migrated from UserVoice

**Created By:** Michael Taylor
**Created On:** 2017/10/08 03:08:54 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment] 2018-06-20 00:15
Duplicate of #50

**Closed by dend** 2018-06-20 00:15 UTC
Labels: assigned-to-pm, bug, in-progress, logged-request, triaged
