### ISSUE TITLE
Q# Project types do not show under Visual C# new projects

### ISSUE THREAD

**Issue by RexPersicus** [MicrosoftDocs/feedback#318] opened 2018-04-22 16:10 UTC
# Idea Title

Do not have the Q# Application or Q# Library or any other Q# project type listed under Visual C# when I try to initiate a new project, despite successful installation of VS Community and Q# Dev Kit and successful test run of Teleportation Sample.

## Issue Details

I have successfully installed VS Community version and Quantum Development Kit following Microsoft website's instruction - and got the "Installation Successful" notification - and connected to the Q# sample project on GitHub and successfully executed the test project. (Windows 10 64bit)

Now when I am trying to initiate a new Q# project, following the instruction, I cannot find any Q# project type under the Visual C# project type or anywhere else.

I also noticed when in VS I go to Help => About Visual Studio, it does not show Q# as a Installed Product which is strange as the test project runs as described with no errors.

Your help is appreciated!
Rex

**Comment by Powerhelmsman** [comment] 2018-04-23 15:52
@RexPersicus Can you provide the instruction link?

**Comment by RexPersicus** [comment] 2018-04-24 02:34
Sure. This is the link:

https://docs.microsoft.com/en-us/quantum/quantum-installconfig?view=qsharp-preview&tabs=tabid-vs2017

**Comment by RexPersicus** [comment] 2018-04-24 02:36
That was the link to the installation instruction ... this the link for writing the sample Q# program which starts with initiating a Q# project under Visual C# section:

https://docs.microsoft.com/en-us/quantum/quantum-writeaquantumprogram?view=qsharp-preview&tabs=tabid-vs2017

**Comment by dend** [comment] 2018-04-28 01:17
@QuantumWriter @tcNickolas do you have any insights here?

**Comment by tcNickolas** [comment] 2018-05-08 21:53
@RexPersicus This sounds like Quantum Development Kit didn't get installed after all. It is possible to build and execute existing projects without the extension. Do you have syntax highlight in .qs files? It is another indication of whether the extension was installed successfully.

**Comment by RexPersicus** [comment] 2018-05-08 23:40
@tcNickolas as I mentioned, I can run the test Q# project with no issues and get the expected results. Q# kit is installed but somehow it does not show under Visual Studio as a new project type. My guess is somehow Anaconda that I have installed is interfering with its showing in Visual Studio, since my friend who has a similar machine and OS can see it listed and the only difference between our machines is that I have Anaconda.

**Comment by Powerhelmsman** [comment] 2018-05-25 23:27
@dend Any updates

**Comment by dend** [comment] 2018-05-29 17:05
This is a question for @tcNickolas

**Comment by Powerhelmsman** [comment] 2018-06-20 23:11
Sent a email to @tcNickolas to follow up.

**Comment by tcNickolas** [comment] 2018-06-20 23:39
@RexPersicus I don't have any suggestions on troubleshooting this; on my machine with Anaconda the extension was installed successfully, so I can't reproduce the suspect scenario. Have you tried installing the extension again? Is it possible that it got installed to a different version of Visual Studio than the one you're using? You can also try Quantum Development Kit for VS Code and see if that works for you.

P.S. This is not a documentation issue and doesn't belong to this repository. The official support channel for Quantum Development Kit is [UserVoice](https://quantum.uservoice.com/forums/906943-setup-and-visual-studio-vs-code-integration). If your issue is not resolved, please create an "idea" there so that the team can follow up.

**Comment by Powerhelmsman** [comment] 2018-06-21 00:14
@RexPersicus I will close the issue now. If you have any question related to it, we can reopen it and continue the discussion.

**Closed by Powerhelmsman** 2018-06-21 00:14 UTC
Labels: content, triaged
