### ISSUE TITLE
Many, many, many of the docs.microsoft.com links are broken!

### ISSUE THREAD

**Issue by sidecut** [MicrosoftDocs/feedback#274] opened 2018-03-30 20:58 UTC
Steps to reproduce:

1. Go to https://docs.microsoft.com/en-us/dotnet/api/
2. Search for a .NET class, for example `NullReferenceException`
3. Click the link
4. Expected behavior: see the documentation page for that class
5. Actual behavior: a giant 404 graphic. Note that there is _no_ redirect to an error page; the URL is the expected localized URL (e.g. en-us) but the content is gone. Example: https://docs.microsoft.com/en-us/dotnet/api/system.nullreferenceexception

**Comment by Powerhelmsman** [comment] 2018-03-30 21:01
@dend Can you take a look at this? A lot of pages are broken now.

**Comment by sidecut** [comment] 2018-03-30 21:07
Possibly only the .../api/... pages.

**Comment by Powerhelmsman** [comment] 2018-03-30 21:20
@mairaw It seems something wrong when team built content.

**Comment by mairaw** [comment] 2018-03-30 21:28
We’re looking into it.

**Comment by sidecut** [comment] 2018-03-30 21:33
I've been there. Devops is still being perfected.

**Comment by dend** [comment] 2018-03-30 22:11
We've identified the root cause and are working on a fix.

**Comment by mairaw** [comment] 2018-03-31 22:05
I think we can close this one now @dend. Thanks @sidecut!

**Comment by sidecut** [comment] 2018-03-31 22:40
I'm glad I could help. When I first noticed, I thought, "Who the heck can I contact about this?" And then there it was, right on the web page, so you guys make it easy to report these issues. Thanks for the responsiveness. Microsoft has become a marvelous mix of a huge company that has a small company's nimbleness when it counts. Well, at least the Dev Div. I have no experience reporting Windows or Office issues.

**Closed** 2018-04-01 02:58 UTC
Labels: bug, triaged
