### ISSUE TITLE
Error of css

### ISSUE THREAD

**Issue by sushilkumar4051** [MicrosoftDocs/feedback#1168] opened 2019-02-17 05:44 UTC
https://developer.microsoft.com/en-us/advocates/index.html

Open this page some css error occur on this page 
Check  User 

Ryan Levick
@ryan_levick

Rust / Functional Programming / JavaScript/TypeScript / Architecture

its content showing outside the div

**Comment by mairaw** [comment] 2019-02-18 21:49
I can't repro this @sushilkumar4051:
![image](https://user-images.githubusercontent.com/12971179/52977884-ea87a000-3383-11e9-8955-934c5b1bf8c0.png)

What's the browser that you're using?

**Comment by sushilkumar4051** [comment] 2019-02-20 14:12
Hello,

   i used chorme browser and it display like that
[image: image.png]

**Comment by mairaw** [comment] 2019-04-03 06:46
Attachments unfortunately are not shown when you reply by e-mail 😢

**Comment by mairaw** [comment] 2023-05-11 00:11
Given we could not reproduce, I'm closing this issue. If you have more information about this, please let us know and we can reopen it.

**Closed by mairaw** 2023-05-11 00:11 UTC
Labels: Pri3
