### ISSUE TITLE
Retry Policy docs is giving 404

### ISSUE THREAD

**Issue by ansahdev** [MicrosoftDocs/feedback#1424] opened 2019-04-24 19:15 UTC
**Describe the bug**
Previously working link: https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.retrypolicies.exponentialretry.-ctor?view=azure-dotnet#Microsoft_WindowsAzure_Storage_RetryPolicies_ExponentialRetry__ctor_System_TimeSpan_System_Int32_ is not working

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.retrypolicies.exponentialretry.-ctor?view=azure-dotnet#Microsoft_WindowsAzure_Storage_RetryPolicies_ExponentialRetry__ctor_System_TimeSpan_System_Int32_'
2. See error - 404

**Expected behavior**
Documentation is available

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows 10
 - Browser [e.g. chrome, safari] : Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dendeli-msft** [comment] 2019-05-03 19:04
Duplicate of #1446

**Closed by dendeli-msft** 2019-05-03 19:04 UTC
