### ISSUE TITLE
Offer a peak at the live source code where possible

### ISSUE THREAD

**Issue by tekguy** [MicrosoftDocs/feedback#438] opened 2018-06-14 19:46 UTC
It would be neat to be able to view the source code along with the documentation. 

For example on https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.challenge?view=aspnetcore-2.1 

Instead of the user having to download the ASPNet MVC project, maybe offer a peak of the Challenge method (or the ControllerBase class). 

The method signature is great but being able to view the source code can provide some more insight:

https://github.com/aspnet/Mvc/blob/84c8db5aaeb537118d427c6cd0c653abb06db5d3/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs#L2175

**Comment by Powerhelmsman** [comment] 2018-06-14 20:30
@dend Can take this under consideration?

**Comment by Powerhelmsman** [comment] 2018-06-14 20:31
#log-suggestion @dend

**Comment by botcrane** [comment] 2018-06-14 20:31
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=25596) logged.

**Comment by dend** [comment] 2018-06-19 18:54
Duplicate of #433

**Closed by dend** 2018-06-19 18:54 UTC
Labels: enhancement, logged-request, triaged

**Comment by gewarren** [comment] 2024-04-04 17:25
Great news - the core .NET libraries now have links to source code!
Example: https://learn.microsoft.com/dotnet/api/system.string.chars?view=net-8.0
