### ISSUE TITLE
Missing links in a page "Cannot open a database created with a previous version of your application. (Error 3041)"

### ISSUE THREAD

**Issue by tygrus2** [MicrosoftDocs/feedback#1739] opened 2019-07-16 07:52 UTC
This page has links which are missing (out-of-date). [Cannot open a database created with a previous version of your application. (Error 3041)](https://docs.microsoft.com/en-us/office/vba/access/concepts/miscellaneous/cannot-open-a-database-created-with-a-previous-version-of-your-applicationerror)
Error="404 – Page not found"

* Application.CompactRepair method (Access)
https://msdn.microsoft.com/library/4820fd79-d907-21bc-0ad5-5fc096c1ef3b%28Office.15%29.aspx

* Compact and Repair a Database
https://msdn.microsoft.com/library/5ad4e6b1-abfd-3f89-5c80-9e41397a96e8%28Office.15%29.aspx

It appears users have lost functionality and access to old files because Microsoft has a short attention span.

**Comment by ryanmajidi** [comment] 2019-07-18 21:05
duplicate of https://github.com/MicrosoftDocs/feedback/issues/1740

**Closed by ryanmajidi** 2019-07-18 21:05 UTC
Labels: duplicate
