### ISSUE TITLE
Make it easier to find pages using Google search

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#92] opened 2018-03-06 22:52 UTC
Usually when I'm looking for information I'll do a search on Google. For instance when searching a method in the framework API, like "Convert.ChangeType". Currently it will always point to msdn.microsoft.com and it is impossible for me to find the page I want at docs.microsoft.com even when using "site:". It either just doesn't find it or it will be a page not in English. Bing also doesn't show docs.microsoft.com on the first search page.

The API pages on msdn.microsoft.com have a link to docs.microsoft.com but then I have to type the search query again, which is not a good experience.

----------
⚠ Idea migrated from UserVoice

**Created By:** Herman Eldering
**Created On:** 2017/11/16 08:08:32 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment] 2018-03-07 01:33
Work in progress as we are migrating content from MSDN to docs.

**Comment by dend** [comment] 2018-05-18 22:20
Let's log a suggestion here #log-suggestion @dend @botcrane

**Comment by dend** [comment] 2018-05-18 22:26
#log-suggestion @dend @botcrane

**Comment by dend** [comment] 2018-05-18 22:28
#log-suggestion @dend @botcrane

**Comment by botcrane** [comment] 2018-05-18 22:28
Failed to submit internal item.

**Comment by dend** [comment] 2018-05-18 22:33
#log-suggestion @dend @botcrane

**Comment by botcrane** [comment] 2018-05-18 22:33
Failed to submit internal item.

**Comment by dend** [comment] 2018-05-18 22:36
#log-suggestion @dend @botcrane

**Comment by botcrane** [comment] 2018-05-18 22:36
Failed to submit internal item.

**Comment by dend** [comment] 2018-05-18 22:40
#log-suggestion @dend @botcrane

**Comment by botcrane** [comment] 2018-05-18 22:40
Failed to submit internal item.

**Comment by dend** [comment] 2018-05-18 22:57
#log-suggestion @dend @botcrane

**Comment by botcrane** [comment] 2018-05-18 22:57
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21332) logged.

**Comment by dend** [comment] 2018-05-18 22:57
#log-suggestion @botcrane

**Comment by botcrane** [comment] 2018-05-18 22:58
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21333) logged.

**Comment by dend** [comment] 2018-05-18 22:58
test

**Comment by dend** [comment] 2018-06-20 00:12
Duplicate of #50

**Closed by dend** 2018-06-20 00:12 UTC
Labels: assigned-to-pm, in-progress, triaged
