### ISSUE TITLE
Almost can't read the Title of this page (yellow background with gray text)

### ISSUE THREAD

**Issue by icaropn** [MicrosoftDocs/feedback#345] opened 2018-05-03 15:24 UTC
Problem:
The contrast of those colors (bg x text color) isn't so good.

![image](https://user-images.githubusercontent.com/6773308/39586159-6fcba7a2-4ec4-11e8-983f-82f9fd0bed0b.png)

**Comment by dend** [comment] 2018-05-03 18:27
Duplicate of #338

**Closed by dend** 2018-05-03 18:27 UTC
