### ISSUE TITLE
Better Searching Capability

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#78] opened 2018-03-06 22:52 UTC
_No details provided._

----------
⚠ Idea migrated from UserVoice

**Created By:** Robert Haluska
**Created On:** 2017/12/07 19:47:38 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment] 2018-03-07 01:32
Given that there is not a lot of detail, resolving as duplicate of #148.

**Closed by dend** 2018-03-07 01:32 UTC
Labels: duplicate, triaged
