### ISSUE TITLE
Tutorials in ePub

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#67] opened 2018-03-06 22:52 UTC
Make relevant documentation available in ePub format so we can read on devices at our leisure

----------
⚠ Idea migrated from UserVoice

**Created By:** Shelly
**Created On:** 2017/12/08 16:05:49 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment] 2018-03-07 02:19
Closing as duplicate of #186

**Closed by dend** 2018-03-07 02:19 UTC
